DROP TABLE IF EXISTS `CONTENT_ASSOC_TYPE`;
CREATE TABLE CONTENT_ASSOC_TYPE (
    CONTENT_ASSOC_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CONTENT_ASSOC_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PERIOD_TYPE`;
CREATE TABLE PERIOD_TYPE (
    PERIOD_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    PERIOD_LENGTH DECIMAL(20,0) ,
    UOM_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PERIOD_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PARTY_IDENTIFICATION_TYPE`;
CREATE TABLE PARTY_IDENTIFICATION_TYPE (
    PARTY_IDENTIFICATION_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PARTY_IDENTIFICATION_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `DATA_CATEGORY`;
CREATE TABLE DATA_CATEGORY (
    DATA_CATEGORY_ID BIGINT auto_increment NOT NULL,
    PARENT_CATEGORY_ID BIGINT ,
    CATEGORY_NAME VARCHAR(100) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`DATA_CATEGORY_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CONTENT_TYPE`;
CREATE TABLE CONTENT_TYPE (
    CONTENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CONTENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ROLE_TYPE`;
CREATE TABLE ROLE_TYPE (
    ROLE_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ROLE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SHIPMENT_GATEWAY_CONFIG_TYPE`;
CREATE TABLE SHIPMENT_GATEWAY_CONFIG_TYPE (
    SHIPMENT_GATEWAY_CONF_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SHIPMENT_GATEWAY_CONF_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CUSTOM_METHOD`;
CREATE TABLE CUSTOM_METHOD (
    CUSTOM_METHOD_ID BIGINT auto_increment NOT NULL,
    CUSTOM_METHOD_TYPE_ID BIGINT ,
    CUSTOM_METHOD_NAME VARCHAR(255) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CUSTOM_METHOD_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SHIPMENT_CONTACT_MECH_TYPE`;
CREATE TABLE SHIPMENT_CONTACT_MECH_TYPE (
    SHIPMENT_CONTACT_MECH_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SHIPMENT_CONTACT_MECH_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CUST_REQUEST_RESOLUTION`;
CREATE TABLE CUST_REQUEST_RESOLUTION (
    CUST_REQUEST_RESOLUTION_ID BIGINT auto_increment NOT NULL,
    CUST_REQUEST_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CUST_REQUEST_RESOLUTION_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `BUDGET_ITEM_TYPE`;
CREATE TABLE BUDGET_ITEM_TYPE (
    BUDGET_ITEM_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`BUDGET_ITEM_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SUBSCRIPTION_TYPE`;
CREATE TABLE SUBSCRIPTION_TYPE (
    SUBSCRIPTION_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SUBSCRIPTION_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PAYMENT_GROUP_TYPE`;
CREATE TABLE PAYMENT_GROUP_TYPE (
    PAYMENT_GROUP_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PAYMENT_GROUP_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FILE_EXTENSION`;
CREATE TABLE FILE_EXTENSION (
    FILE_EXTENSION_ID BIGINT auto_increment NOT NULL,
    MIME_TYPE_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FILE_EXTENSION_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SEGMENT_GROUP_TYPE`;
CREATE TABLE SEGMENT_GROUP_TYPE (
    SEGMENT_GROUP_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SEGMENT_GROUP_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `DATA_SOURCE_TYPE`;
CREATE TABLE DATA_SOURCE_TYPE (
    DATA_SOURCE_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`DATA_SOURCE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `DATA_TEMPLATE_TYPE`;
CREATE TABLE DATA_TEMPLATE_TYPE (
    DATA_TEMPLATE_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    EXTENSION VARCHAR(60) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`DATA_TEMPLATE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `WORK_EFFORT_CONTENT_TYPE`;
CREATE TABLE WORK_EFFORT_CONTENT_TYPE (
    WORK_EFFORT_CONTENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`WORK_EFFORT_CONTENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GEO_ASSOC`;
CREATE TABLE GEO_ASSOC (
    GEO_ID BIGINT NOT NULL,
    GEO_ID_TO BIGINT NOT NULL,
    GEO_ASSOC_TYPE_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_GEO_ASSOC (GEO_ID, GEO_ID_TO) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `USER_PREFERENCE`;
CREATE TABLE USER_PREFERENCE (
    USER_LOGIN_ID BIGINT NOT NULL,
    USER_PREF_TYPE_ID BIGINT NOT NULL,
    USER_PREF_GROUP_TYPE_ID BIGINT ,
    USER_PREF_VALUE VARCHAR(255) ,
    USER_PREF_DATA_TYPE BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_USER_PREFERENCE (USER_LOGIN_ID, USER_PREF_TYPE_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_PRICE_PURPOSE`;
CREATE TABLE PRODUCT_PRICE_PURPOSE (
    PRODUCT_PRICE_PURPOSE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_PRICE_PURPOSE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SURVEY_APPL_TYPE`;
CREATE TABLE SURVEY_APPL_TYPE (
    SURVEY_APPL_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SURVEY_APPL_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SHIPMENT_GATEWAY_FEDEX`;
CREATE TABLE SHIPMENT_GATEWAY_FEDEX (
    SHIPMENT_GATEWAY_CONFIG_ID BIGINT auto_increment NOT NULL,
    CONNECT_URL VARCHAR(255) ,
    CONNECT_SOAP_URL VARCHAR(255) ,
    CONNECT_TIMEOUT DECIMAL(20,0) ,
    ACCESS_ACCOUNT_NBR VARCHAR(255) ,
    ACCESS_METER_NUMBER VARCHAR(255) ,
    ACCESS_USER_KEY VARCHAR(255) ,
    ACCESS_USER_PWD VARCHAR(255) ,
    LABEL_IMAGE_TYPE VARCHAR(60) ,
    DEFAULT_DROPOFF_TYPE VARCHAR(255) ,
    DEFAULT_PACKAGING_TYPE VARCHAR(255) ,
    TEMPLATE_SHIPMENT VARCHAR(255) ,
    TEMPLATE_SUBSCRIPTION VARCHAR(255) ,
    RATE_ESTIMATE_TEMPLATE VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SHIPMENT_GATEWAY_CONFIG_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CONTACT_MECH_TYPE`;
CREATE TABLE CONTACT_MECH_TYPE (
    CONTACT_MECH_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CONTACT_MECH_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SURVEY_QUESTION_TYPE`;
CREATE TABLE SURVEY_QUESTION_TYPE (
    SURVEY_QUESTION_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SURVEY_QUESTION_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CONTENT_OPERATION`;
CREATE TABLE CONTENT_OPERATION (
    CONTENT_OPERATION_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CONTENT_OPERATION_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ORDER_DENYLIST_TYPE`;
CREATE TABLE ORDER_DENYLIST_TYPE (
    ORDER_DENYLIST_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ORDER_DENYLIST_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `RETURN_ADJUSTMENT_TYPE`;
CREATE TABLE RETURN_ADJUSTMENT_TYPE (
    RETURN_ADJUSTMENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`RETURN_ADJUSTMENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_TYPE`;
CREATE TABLE PRODUCT_TYPE (
    PRODUCT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    IS_PHYSICAL CHAR(1) ,
    IS_DIGITAL CHAR(1) ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `RETURN_TYPE`;
CREATE TABLE RETURN_TYPE (
    RETURN_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    SEQUENCE_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`RETURN_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `TAX_AUTHORITY_ASSOC_TYPE`;
CREATE TABLE TAX_AUTHORITY_ASSOC_TYPE (
    TAX_AUTHORITY_ASSOC_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`TAX_AUTHORITY_ASSOC_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `DATA_SOURCE`;
CREATE TABLE DATA_SOURCE (
    DATA_SOURCE_ID BIGINT auto_increment NOT NULL,
    DATA_SOURCE_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`DATA_SOURCE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GEO`;
CREATE TABLE GEO (
    GEO_ID BIGINT auto_increment NOT NULL,
    GEO_TYPE_ID BIGINT ,
    GEO_NAME VARCHAR(100) ,
    GEO_CODE VARCHAR(60) ,
    GEO_SEC_CODE VARCHAR(60) ,
    ABBREVIATION VARCHAR(60) ,
    WELL_KNOWN_TEXT LONGTEXT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GEO_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CONTACT_MECH_TYPE_PURPOSE`;
CREATE TABLE CONTACT_MECH_TYPE_PURPOSE (
    CONTACT_MECH_TYPE_ID BIGINT NOT NULL,
    CONTACT_MECH_PURPOSE_TYPE_ID BIGINT NOT NULL,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_CONTACT_MECH_TYPE_PURPOSE (CONTACT_MECH_TYPE_ID, CONTACT_MECH_PURPOSE_TYPE_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `TRACKING_CODE_TYPE`;
CREATE TABLE TRACKING_CODE_TYPE (
    TRACKING_CODE_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`TRACKING_CODE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_STORE_GROUP`;
CREATE TABLE PRODUCT_STORE_GROUP (
    PRODUCT_STORE_GROUP_ID BIGINT auto_increment NOT NULL,
    PRODUCT_STORE_GROUP_TYPE_ID BIGINT ,
    PRIMARY_PARENT_GROUP_ID BIGINT ,
    PRODUCT_STORE_GROUP_NAME VARCHAR(100) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_STORE_GROUP_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SHOPPING_LIST_TYPE`;
CREATE TABLE SHOPPING_LIST_TYPE (
    SHOPPING_LIST_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SHOPPING_LIST_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `EMPL_POSITION_TYPE`;
CREATE TABLE EMPL_POSITION_TYPE (
    EMPL_POSITION_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`EMPL_POSITION_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `RETURN_REASON`;
CREATE TABLE RETURN_REASON (
    RETURN_REASON_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    SEQUENCE_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`RETURN_REASON_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `RESPONSIBILITY_TYPE`;
CREATE TABLE RESPONSIBILITY_TYPE (
    RESPONSIBILITY_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`RESPONSIBILITY_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FIXED_ASSET_TYPE`;
CREATE TABLE FIXED_ASSET_TYPE (
    FIXED_ASSET_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FIXED_ASSET_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CONTENT_PURPOSE_OPERATION`;
CREATE TABLE CONTENT_PURPOSE_OPERATION (
    CONTENT_PURPOSE_TYPE_ID BIGINT NOT NULL,
    CONTENT_OPERATION_ID BIGINT NOT NULL,
    ROLE_TYPE_ID BIGINT NOT NULL,
    STATUS_ID BIGINT NOT NULL,
    PRIVILEGE_ENUM_ID BIGINT NOT NULL,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_CONTENT_PURPOSE_OPERATION (CONTENT_PURPOSE_TYPE_ID, CONTENT_OPERATION_ID, ROLE_TYPE_ID, STATUS_ID, PRIVILEGE_ENUM_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PROD_CATALOG_CATEGORY_TYPE`;
CREATE TABLE PROD_CATALOG_CATEGORY_TYPE (
    PROD_CATALOG_CATEGORY_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PROD_CATALOG_CATEGORY_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SHIPMENT_GATEWAY_USPS`;
CREATE TABLE SHIPMENT_GATEWAY_USPS (
    SHIPMENT_GATEWAY_CONFIG_ID BIGINT auto_increment NOT NULL,
    CONNECT_URL VARCHAR(255) ,
    CONNECT_URL_LABELS VARCHAR(255) ,
    CONNECT_TIMEOUT DECIMAL(20,0) ,
    ACCESS_USER_ID VARCHAR(255) ,
    ACCESS_PASSWORD VARCHAR(255) ,
    MAX_ESTIMATE_WEIGHT DECIMAL(20,0) ,
    TEST VARCHAR(60) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SHIPMENT_GATEWAY_CONFIG_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ENTITY_GROUP`;
CREATE TABLE ENTITY_GROUP (
    ENTITY_GROUP_ID BIGINT auto_increment NOT NULL,
    ENTITY_GROUP_NAME VARCHAR(100) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ENTITY_GROUP_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_METER_TYPE`;
CREATE TABLE PRODUCT_METER_TYPE (
    PRODUCT_METER_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    DEFAULT_UOM_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_METER_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `DEDUCTION_TYPE`;
CREATE TABLE DEDUCTION_TYPE (
    DEDUCTION_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`DEDUCTION_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GL_FISCAL_TYPE`;
CREATE TABLE GL_FISCAL_TYPE (
    GL_FISCAL_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GL_FISCAL_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SYSTEM_PROPERTY`;
CREATE TABLE SYSTEM_PROPERTY (
    SYSTEM_RESOURCE_ID BIGINT NOT NULL,
    SYSTEM_PROPERTY_ID BIGINT NOT NULL,
    SYSTEM_PROPERTY_VALUE VARCHAR(255) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_SYSTEM_PROPERTY (SYSTEM_RESOURCE_ID, SYSTEM_PROPERTY_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `MIME_TYPE`;
CREATE TABLE MIME_TYPE (
    MIME_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`MIME_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `MRP_EVENT_TYPE`;
CREATE TABLE MRP_EVENT_TYPE (
    MRP_EVENT_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`MRP_EVENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CONTENT_PURPOSE_TYPE`;
CREATE TABLE CONTENT_PURPOSE_TYPE (
    CONTENT_PURPOSE_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CONTENT_PURPOSE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_CATEGORY_CONTENT_TYPE`;
CREATE TABLE PRODUCT_CATEGORY_CONTENT_TYPE (
    PROD_CAT_CONTENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PROD_CAT_CONTENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FIXED_ASSET_STD_COST_TYPE`;
CREATE TABLE FIXED_ASSET_STD_COST_TYPE (
    FIXED_ASSET_STD_COST_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FIXED_ASSET_STD_COST_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `EMPL_LEAVE_TYPE`;
CREATE TABLE EMPL_LEAVE_TYPE (
    LEAVE_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`LEAVE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CHARACTER_SET`;
CREATE TABLE CHARACTER_SET (
    CHARACTER_SET_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CHARACTER_SET_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `RATE_TYPE`;
CREATE TABLE RATE_TYPE (
    RATE_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`RATE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `TRAINING_CLASS_TYPE`;
CREATE TABLE TRAINING_CLASS_TYPE (
    TRAINING_CLASS_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`TRAINING_CLASS_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SECURITY_PERMISSION`;
CREATE TABLE SECURITY_PERMISSION (
    PERMISSION_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PERMISSION_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_PRICE_TYPE`;
CREATE TABLE PRODUCT_PRICE_TYPE (
    PRODUCT_PRICE_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_PRICE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CONTACT_MECH_PURPOSE_TYPE`;
CREATE TABLE CONTACT_MECH_PURPOSE_TYPE (
    CONTACT_MECH_PURPOSE_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CONTACT_MECH_PURPOSE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `VISUAL_THEME_SET`;
CREATE TABLE VISUAL_THEME_SET (
    VISUAL_THEME_SET_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`VISUAL_THEME_SET_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ENUMERATION`;
CREATE TABLE ENUMERATION (
    ENUM_ID BIGINT auto_increment NOT NULL,
    ENUM_TYPE_ID BIGINT ,
    ENUM_CODE VARCHAR(60) ,
    SEQUENCE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ENUM_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `STANDARD_LANGUAGE`;
CREATE TABLE STANDARD_LANGUAGE (
    STANDARD_LANGUAGE_ID BIGINT auto_increment NOT NULL,
    LANG_CODE3T VARCHAR(10) ,
    LANG_CODE3B VARCHAR(10) ,
    LANG_CODE2 VARCHAR(10) ,
    LANG_NAME VARCHAR(60) ,
    LANG_FAMILY VARCHAR(60) ,
    LANG_CHARSET VARCHAR(60) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`STANDARD_LANGUAGE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `COUNTRY_TELE_CODE`;
CREATE TABLE COUNTRY_TELE_CODE (
    COUNTRY_CODE BIGINT auto_increment NOT NULL,
    TELE_CODE VARCHAR(60) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`COUNTRY_CODE`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_ASSOC_TYPE`;
CREATE TABLE PRODUCT_ASSOC_TYPE (
    PRODUCT_ASSOC_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_ASSOC_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ORDER_ITEM_TYPE`;
CREATE TABLE ORDER_ITEM_TYPE (
    ORDER_ITEM_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ORDER_ITEM_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `RETURN_HEADER_TYPE`;
CREATE TABLE RETURN_HEADER_TYPE (
    RETURN_HEADER_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`RETURN_HEADER_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `WORK_EFFORT_ASSOC_TYPE`;
CREATE TABLE WORK_EFFORT_ASSOC_TYPE (
    WORK_EFFORT_ASSOC_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`WORK_EFFORT_ASSOC_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `TECH_DATA_CALENDAR`;
CREATE TABLE TECH_DATA_CALENDAR (
    CALENDAR_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    CALENDAR_WEEK_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CALENDAR_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GEO_TYPE`;
CREATE TABLE GEO_TYPE (
    GEO_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GEO_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GL_XBRL_CLASS`;
CREATE TABLE GL_XBRL_CLASS (
    GL_XBRL_CLASS_ID BIGINT auto_increment NOT NULL,
    PARENT_GL_XBRL_CLASS_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GL_XBRL_CLASS_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `TECH_DATA_CALENDAR_WEEK`;
CREATE TABLE TECH_DATA_CALENDAR_WEEK (
    CALENDAR_WEEK_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    MONDAY_START_TIME TIME(3) ,
    MONDAY_CAPACITY DOUBLE ,
    TUESDAY_START_TIME TIME(3) ,
    TUESDAY_CAPACITY DOUBLE ,
    WEDNESDAY_START_TIME TIME(3) ,
    WEDNESDAY_CAPACITY DOUBLE ,
    THURSDAY_START_TIME TIME(3) ,
    THURSDAY_CAPACITY DOUBLE ,
    FRIDAY_START_TIME TIME(3) ,
    FRIDAY_CAPACITY DOUBLE ,
    SATURDAY_START_TIME TIME(3) ,
    SATURDAY_CAPACITY DOUBLE ,
    SUNDAY_START_TIME TIME(3) ,
    SUNDAY_CAPACITY DOUBLE ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CALENDAR_WEEK_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PAYMENT_GATEWAY_CONFIG_TYPE`;
CREATE TABLE PAYMENT_GATEWAY_CONFIG_TYPE (
    PAYMENT_GATEWAY_CONFIG_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PAYMENT_GATEWAY_CONFIG_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FACILITY_TYPE`;
CREATE TABLE FACILITY_TYPE (
    FACILITY_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FACILITY_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `EMPL_LEAVE_REASON_TYPE`;
CREATE TABLE EMPL_LEAVE_REASON_TYPE (
    EMPL_LEAVE_REASON_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`EMPL_LEAVE_REASON_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_AVERAGE_COST_TYPE`;
CREATE TABLE PRODUCT_AVERAGE_COST_TYPE (
    PRODUCT_AVERAGE_COST_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_AVERAGE_COST_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_MAINT_TYPE`;
CREATE TABLE PRODUCT_MAINT_TYPE (
    PRODUCT_MAINT_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    PARENT_TYPE_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_MAINT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `INVENTORY_ITEM_TYPE`;
CREATE TABLE INVENTORY_ITEM_TYPE (
    INVENTORY_ITEM_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`INVENTORY_ITEM_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SHIPMENT_GATEWAY_CONFIG`;
CREATE TABLE SHIPMENT_GATEWAY_CONFIG (
    SHIPMENT_GATEWAY_CONFIG_ID BIGINT auto_increment NOT NULL,
    SHIPMENT_GATEWAY_CONF_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SHIPMENT_GATEWAY_CONFIG_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SERVER_HIT_TYPE`;
CREATE TABLE SERVER_HIT_TYPE (
    HIT_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`HIT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `TERM_TYPE`;
CREATE TABLE TERM_TYPE (
    TERM_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`TERM_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `BUDGET_TYPE`;
CREATE TABLE BUDGET_TYPE (
    BUDGET_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`BUDGET_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `INVOICE_ITEM_TYPE_MAP`;
CREATE TABLE INVOICE_ITEM_TYPE_MAP (
    INVOICE_ITEM_MAP_KEY BIGINT NOT NULL,
    INVOICE_TYPE_ID BIGINT NOT NULL,
    INVOICE_ITEM_TYPE_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_INVOICE_ITEM_TYPE_MAP (INVOICE_ITEM_MAP_KEY, INVOICE_TYPE_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `WEB_SITE_CONTENT_TYPE`;
CREATE TABLE WEB_SITE_CONTENT_TYPE (
    WEB_SITE_CONTENT_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`WEB_SITE_CONTENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `WEB_ANALYTICS_TYPE`;
CREATE TABLE WEB_ANALYTICS_TYPE (
    WEB_ANALYTICS_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`WEB_ANALYTICS_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `WORK_REQ_FULF_TYPE`;
CREATE TABLE WORK_REQ_FULF_TYPE (
    WORK_REQ_FULF_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`WORK_REQ_FULF_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GL_ACCOUNT_TYPE`;
CREATE TABLE GL_ACCOUNT_TYPE (
    GL_ACCOUNT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GL_ACCOUNT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `USER_PREF_GROUP_TYPE`;
CREATE TABLE USER_PREF_GROUP_TYPE (
    USER_PREF_GROUP_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`USER_PREF_GROUP_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FACILITY_ASSOC_TYPE`;
CREATE TABLE FACILITY_ASSOC_TYPE (
    FACILITY_ASSOC_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FACILITY_ASSOC_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SHIPMENT_TYPE`;
CREATE TABLE SHIPMENT_TYPE (
    SHIPMENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SHIPMENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ORDER_TYPE`;
CREATE TABLE ORDER_TYPE (
    ORDER_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ORDER_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PARTY_CLASSIFICATION_TYPE`;
CREATE TABLE PARTY_CLASSIFICATION_TYPE (
    PARTY_CLASSIFICATION_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PARTY_CLASSIFICATION_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `RETURN_ITEM_TYPE_MAP`;
CREATE TABLE RETURN_ITEM_TYPE_MAP (
    RETURN_ITEM_MAP_KEY BIGINT NOT NULL,
    RETURN_HEADER_TYPE_ID BIGINT NOT NULL,
    RETURN_ITEM_TYPE_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_RETURN_ITEM_TYPE_MAP (RETURN_ITEM_MAP_KEY, RETURN_HEADER_TYPE_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GL_ACCOUNT_CATEGORY_TYPE`;
CREATE TABLE GL_ACCOUNT_CATEGORY_TYPE (
    GL_ACCOUNT_CATEGORY_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GL_ACCOUNT_CATEGORY_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_FEATURE_APPL_TYPE`;
CREATE TABLE PRODUCT_FEATURE_APPL_TYPE (
    PRODUCT_FEATURE_APPL_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_FEATURE_APPL_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CONTACT_LIST_TYPE`;
CREATE TABLE CONTACT_LIST_TYPE (
    CONTACT_LIST_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CONTACT_LIST_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `INVOICE_ITEM_TYPE`;
CREATE TABLE INVOICE_ITEM_TYPE (
    INVOICE_ITEM_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    DEFAULT_GL_ACCOUNT_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`INVOICE_ITEM_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CONTENT_ASSOC_PREDICATE`;
CREATE TABLE CONTENT_ASSOC_PREDICATE (
    CONTENT_ASSOC_PREDICATE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CONTENT_ASSOC_PREDICATE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `WORK_EFFORT_PURPOSE_TYPE`;
CREATE TABLE WORK_EFFORT_PURPOSE_TYPE (
    WORK_EFFORT_PURPOSE_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`WORK_EFFORT_PURPOSE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_PRICE_ACTION_TYPE`;
CREATE TABLE PRODUCT_PRICE_ACTION_TYPE (
    PRODUCT_PRICE_ACTION_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_PRICE_ACTION_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GL_RESOURCE_TYPE`;
CREATE TABLE GL_RESOURCE_TYPE (
    GL_RESOURCE_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GL_RESOURCE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PAYMENT_METHOD_TYPE`;
CREATE TABLE PAYMENT_METHOD_TYPE (
    PAYMENT_METHOD_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    DEFAULT_GL_ACCOUNT_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PAYMENT_METHOD_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FACILITY_GROUP`;
CREATE TABLE FACILITY_GROUP (
    FACILITY_GROUP_ID BIGINT auto_increment NOT NULL,
    FACILITY_GROUP_TYPE_ID BIGINT ,
    PRIMARY_PARENT_GROUP_ID BIGINT ,
    FACILITY_GROUP_NAME VARCHAR(100) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FACILITY_GROUP_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `COUNTRY_ADDRESS_FORMAT`;
CREATE TABLE COUNTRY_ADDRESS_FORMAT (
    GEO_ID BIGINT auto_increment NOT NULL,
    GEO_ASSOC_TYPE_ID BIGINT ,
    REQUIRE_STATE_PROVINCE_ID BIGINT ,
    REQUIRE_POSTAL_CODE CHAR(1) ,
    POSTAL_CODE_REGEX VARCHAR(255) ,
    HAS_POSTAL_CODE_EXT CHAR(1) ,
    REQUIRE_POSTAL_CODE_EXT CHAR(1) ,
    ADDRESS_FORMAT VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GEO_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PARTY_CONTENT_TYPE`;
CREATE TABLE PARTY_CONTENT_TYPE (
    PARTY_CONTENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PARTY_CONTENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FIN_ACCOUNT_TRANS_TYPE`;
CREATE TABLE FIN_ACCOUNT_TRANS_TYPE (
    FIN_ACCOUNT_TRANS_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FIN_ACCOUNT_TRANS_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_FEATURE_TYPE`;
CREATE TABLE PRODUCT_FEATURE_TYPE (
    PRODUCT_FEATURE_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_FEATURE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ENTITY_GROUP_ENTRY`;
CREATE TABLE ENTITY_GROUP_ENTRY (
    ENTITY_GROUP_ID BIGINT NOT NULL,
    ENTITY_OR_PACKAGE VARCHAR(255) NOT NULL,
    APPL_ENUM_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_ENTITY_GROUP_ENTRY (ENTITY_GROUP_ID, ENTITY_OR_PACKAGE) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GOOD_IDENTIFICATION_TYPE`;
CREATE TABLE GOOD_IDENTIFICATION_TYPE (
    GOOD_IDENTIFICATION_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GOOD_IDENTIFICATION_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PROD_CONF_ITEM_CONTENT_TYPE`;
CREATE TABLE PROD_CONF_ITEM_CONTENT_TYPE (
    CONF_ITEM_CONTENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CONF_ITEM_CONTENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `COMMUNICATION_EVENT_PRP_TYP`;
CREATE TABLE COMMUNICATION_EVENT_PRP_TYP (
    COMMUNICATION_EVENT_PRP_TYP_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`COMMUNICATION_EVENT_PRP_TYP_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SUPPLIER_PREF_ORDER`;
CREATE TABLE SUPPLIER_PREF_ORDER (
    SUPPLIER_PREF_ORDER_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SUPPLIER_PREF_ORDER_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `REJECTION_REASON`;
CREATE TABLE REJECTION_REASON (
    REJECTION_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`REJECTION_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SHIPMENT_GATEWAY_UPS`;
CREATE TABLE SHIPMENT_GATEWAY_UPS (
    SHIPMENT_GATEWAY_CONFIG_ID BIGINT auto_increment NOT NULL,
    CONNECT_URL VARCHAR(255) ,
    CONNECT_TIMEOUT DECIMAL(20,0) ,
    SHIPPER_NUMBER VARCHAR(255) ,
    BILL_SHIPPER_ACCOUNT_NUMBER VARCHAR(255) ,
    ACCESS_LICENSE_NUMBER VARCHAR(255) ,
    ACCESS_USER_ID VARCHAR(255) ,
    ACCESS_PASSWORD VARCHAR(255) ,
    SAVE_CERT_INFO VARCHAR(60) ,
    SAVE_CERT_PATH VARCHAR(255) ,
    SHIPPER_PICKUP_TYPE VARCHAR(60) ,
    CUSTOMER_CLASSIFICATION VARCHAR(60) ,
    MAX_ESTIMATE_WEIGHT DECIMAL(18,6) ,
    MIN_ESTIMATE_WEIGHT DECIMAL(18,6) ,
    COD_ALLOW_COD VARCHAR(255) ,
    COD_SURCHARGE_AMOUNT DECIMAL(18,6) ,
    COD_SURCHARGE_CURRENCY_UOM_ID VARCHAR(60) ,
    COD_SURCHARGE_APPLY_TO_PACKAGE VARCHAR(60) ,
    COD_FUNDS_CODE VARCHAR(60) ,
    DEFAULT_RETURN_LABEL_MEMO VARCHAR(255) ,
    DEFAULT_RETURN_LABEL_SUBJECT VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SHIPMENT_GATEWAY_CONFIG_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GL_ACCOUNT_GROUP_TYPE`;
CREATE TABLE GL_ACCOUNT_GROUP_TYPE (
    GL_ACCOUNT_GROUP_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GL_ACCOUNT_GROUP_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ALLOCATION_PLAN_TYPE`;
CREATE TABLE ALLOCATION_PLAN_TYPE (
    PLAN_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    HAS_TABLE CHAR(1) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PLAN_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_CATEGORY_TYPE`;
CREATE TABLE PRODUCT_CATEGORY_TYPE (
    PRODUCT_CATEGORY_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_CATEGORY_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `COUNTRY_CAPITAL`;
CREATE TABLE COUNTRY_CAPITAL (
    COUNTRY_CODE BIGINT auto_increment NOT NULL,
    COUNTRY_CAPITAL VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`COUNTRY_CODE`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `COMMUNICATION_EVENT_TYPE`;
CREATE TABLE COMMUNICATION_EVENT_TYPE (
    COMMUNICATION_EVENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    CONTACT_MECH_TYPE_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`COMMUNICATION_EVENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `TELECOM_METHOD_TYPE`;
CREATE TABLE TELECOM_METHOD_TYPE (
    TELECOM_METHOD_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`TELECOM_METHOD_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `REQUIREMENT_TYPE`;
CREATE TABLE REQUIREMENT_TYPE (
    REQUIREMENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`REQUIREMENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GL_ACCOUNT_GROUP`;
CREATE TABLE GL_ACCOUNT_GROUP (
    GL_ACCOUNT_GROUP_ID BIGINT auto_increment NOT NULL,
    GL_ACCOUNT_GROUP_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GL_ACCOUNT_GROUP_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CUSTOM_METHOD_TYPE`;
CREATE TABLE CUSTOM_METHOD_TYPE (
    CUSTOM_METHOD_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CUSTOM_METHOD_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ORDER_ADJUSTMENT_TYPE`;
CREATE TABLE ORDER_ADJUSTMENT_TYPE (
    ORDER_ADJUSTMENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ORDER_ADJUSTMENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `QUOTE_TYPE`;
CREATE TABLE QUOTE_TYPE (
    QUOTE_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`QUOTE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `RETURN_ITEM_TYPE`;
CREATE TABLE RETURN_ITEM_TYPE (
    RETURN_ITEM_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`RETURN_ITEM_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `DATA_RESOURCE_TYPE`;
CREATE TABLE DATA_RESOURCE_TYPE (
    DATA_RESOURCE_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`DATA_RESOURCE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ORDER_ITEM_ASSOC_TYPE`;
CREATE TABLE ORDER_ITEM_ASSOC_TYPE (
    ORDER_ITEM_ASSOC_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ORDER_ITEM_ASSOC_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FACILITY_GROUP_TYPE`;
CREATE TABLE FACILITY_GROUP_TYPE (
    FACILITY_GROUP_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FACILITY_GROUP_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_FEATURE_IACTN_TYPE`;
CREATE TABLE PRODUCT_FEATURE_IACTN_TYPE (
    PRODUCT_FEATURE_IACTN_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_FEATURE_IACTN_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FIXED_ASSET_PRODUCT_TYPE`;
CREATE TABLE FIXED_ASSET_PRODUCT_TYPE (
    FIXED_ASSET_PRODUCT_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FIXED_ASSET_PRODUCT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `WORK_EFFORT_TYPE`;
CREATE TABLE WORK_EFFORT_TYPE (
    WORK_EFFORT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`WORK_EFFORT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ACCTG_TRANS_TYPE`;
CREATE TABLE ACCTG_TRANS_TYPE (
    ACCTG_TRANS_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ACCTG_TRANS_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `INVOICE_ITEM_ASSOC_TYPE`;
CREATE TABLE INVOICE_ITEM_ASSOC_TYPE (
    INVOICE_ITEM_ASSOC_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`INVOICE_ITEM_ASSOC_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `META_DATA_PREDICATE`;
CREATE TABLE META_DATA_PREDICATE (
    META_DATA_PREDICATE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`META_DATA_PREDICATE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PERF_RATING_TYPE`;
CREATE TABLE PERF_RATING_TYPE (
    PERF_RATING_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PERF_RATING_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `UOM_TYPE`;
CREATE TABLE UOM_TYPE (
    UOM_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`UOM_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `STATUS_ITEM`;
CREATE TABLE STATUS_ITEM (
    STATUS_ID BIGINT auto_increment NOT NULL,
    STATUS_TYPE_ID BIGINT ,
    STATUS_CODE VARCHAR(60) ,
    SEQUENCE_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`STATUS_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `STATUS_VALID_CHANGE`;
CREATE TABLE STATUS_VALID_CHANGE (
    STATUS_ID BIGINT NOT NULL,
    STATUS_ID_TO BIGINT NOT NULL,
    CONDITION_EXPRESSION VARCHAR(255) ,
    TRANSITION_NAME VARCHAR(100) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_STATUS_VALID_CHANGE (STATUS_ID, STATUS_ID_TO) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `QUANTITY_BREAK_TYPE`;
CREATE TABLE QUANTITY_BREAK_TYPE (
    QUANTITY_BREAK_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`QUANTITY_BREAK_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `EMPLOYMENT_APP_SOURCE_TYPE`;
CREATE TABLE EMPLOYMENT_APP_SOURCE_TYPE (
    EMPLOYMENT_APP_SOURCE_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`EMPLOYMENT_APP_SOURCE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PAYMENT_TYPE`;
CREATE TABLE PAYMENT_TYPE (
    PAYMENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PAYMENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `WORK_EFFORT_GOOD_STANDARD_TYPE`;
CREATE TABLE WORK_EFFORT_GOOD_STANDARD_TYPE (
    WORK_EFFORT_GOOD_STD_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`WORK_EFFORT_GOOD_STD_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `COUNTRY_CODE`;
CREATE TABLE COUNTRY_CODE (
    COUNTRY_CODE BIGINT auto_increment NOT NULL,
    COUNTRY_ABBR VARCHAR(60) ,
    COUNTRY_NUMBER VARCHAR(60) ,
    COUNTRY_NAME VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`COUNTRY_CODE`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PARTY_QUAL_TYPE`;
CREATE TABLE PARTY_QUAL_TYPE (
    PARTY_QUAL_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PARTY_QUAL_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PARTY_TYPE`;
CREATE TABLE PARTY_TYPE (
    PARTY_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PARTY_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `MIME_TYPE_HTML_TEMPLATE`;
CREATE TABLE MIME_TYPE_HTML_TEMPLATE (
    MIME_TYPE_ID BIGINT auto_increment NOT NULL,
    TEMPLATE_LOCATION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`MIME_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FIN_ACCOUNT_TYPE`;
CREATE TABLE FIN_ACCOUNT_TYPE (
    FIN_ACCOUNT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    REPLENISH_ENUM_ID BIGINT ,
    IS_REFUNDABLE CHAR(1) ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FIN_ACCOUNT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SHIPMENT_GATEWAY_DHL`;
CREATE TABLE SHIPMENT_GATEWAY_DHL (
    SHIPMENT_GATEWAY_CONFIG_ID BIGINT auto_increment NOT NULL,
    CONNECT_URL VARCHAR(255) ,
    CONNECT_TIMEOUT DECIMAL(20,0) ,
    HEAD_VERSION VARCHAR(60) ,
    HEAD_ACTION VARCHAR(255) ,
    ACCESS_USER_ID VARCHAR(255) ,
    ACCESS_PASSWORD VARCHAR(255) ,
    ACCESS_ACCOUNT_NBR VARCHAR(255) ,
    ACCESS_SHIPPING_KEY VARCHAR(255) ,
    LABEL_IMAGE_FORMAT VARCHAR(60) ,
    RATE_ESTIMATE_TEMPLATE VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SHIPMENT_GATEWAY_CONFIG_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `INVOICE_CONTENT_TYPE`;
CREATE TABLE INVOICE_CONTENT_TYPE (
    INVOICE_CONTENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`INVOICE_CONTENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `TERMINATION_TYPE`;
CREATE TABLE TERMINATION_TYPE (
    TERMINATION_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`TERMINATION_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GL_ACCOUNT_CLASS`;
CREATE TABLE GL_ACCOUNT_CLASS (
    GL_ACCOUNT_CLASS_ID BIGINT auto_increment NOT NULL,
    PARENT_CLASS_ID BIGINT ,
    DESCRIPTION VARCHAR(255) ,
    IS_ASSET_CLASS CHAR(1) ,
    SEQUENCE_NUM DECIMAL(20,0) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GL_ACCOUNT_CLASS_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PARTY_RELATIONSHIP_TYPE`;
CREATE TABLE PARTY_RELATIONSHIP_TYPE (
    PARTY_RELATIONSHIP_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    PARTY_RELATIONSHIP_NAME VARCHAR(100) ,
    DESCRIPTION VARCHAR(255) ,
    ROLE_TYPE_ID_VALID_FROM BIGINT ,
    ROLE_TYPE_ID_VALID_TO BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PARTY_RELATIONSHIP_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `BUDGET_REVIEW_RESULT_TYPE`;
CREATE TABLE BUDGET_REVIEW_RESULT_TYPE (
    BUDGET_REVIEW_RESULT_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    COMMENTS VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`BUDGET_REVIEW_RESULT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ENUMERATION_TYPE`;
CREATE TABLE ENUMERATION_TYPE (
    ENUM_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ENUM_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `DOCUMENT_TYPE`;
CREATE TABLE DOCUMENT_TYPE (
    DOCUMENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`DOCUMENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `TAX_AUTHORITY_RATE_TYPE`;
CREATE TABLE TAX_AUTHORITY_RATE_TYPE (
    TAX_AUTHORITY_RATE_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`TAX_AUTHORITY_RATE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `VARIANCE_REASON`;
CREATE TABLE VARIANCE_REASON (
    VARIANCE_REASON_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`VARIANCE_REASON_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `UOM_CONVERSION`;
CREATE TABLE UOM_CONVERSION (
    UOM_ID BIGINT NOT NULL,
    UOM_ID_TO BIGINT NOT NULL,
    CONVERSION_FACTOR DOUBLE ,
    CUSTOM_METHOD_ID BIGINT ,
    DECIMAL_SCALE DECIMAL(20,0) ,
    ROUNDING_MODE BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    ID BIGINT auto_increment NOT NULL,
    
    PRIMARY KEY (`ID`) , UNIQUE KEY unique_UOM_CONVERSION (UOM_ID, UOM_ID_TO) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PRODUCT_CONTENT_TYPE`;
CREATE TABLE PRODUCT_CONTENT_TYPE (
    PRODUCT_CONTENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PRODUCT_CONTENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `GEO_ASSOC_TYPE`;
CREATE TABLE GEO_ASSOC_TYPE (
    GEO_ASSOC_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`GEO_ASSOC_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `INVOICE_TYPE`;
CREATE TABLE INVOICE_TYPE (
    INVOICE_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`INVOICE_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `BENEFIT_TYPE`;
CREATE TABLE BENEFIT_TYPE (
    BENEFIT_TYPE_ID BIGINT auto_increment NOT NULL,
    BENEFIT_NAME VARCHAR(100) ,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    EMPLOYER_PAID_PERCENTAGE DOUBLE ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`BENEFIT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `UOM`;
CREATE TABLE UOM (
    UOM_ID BIGINT auto_increment NOT NULL,
    UOM_TYPE_ID BIGINT ,
    ABBREVIATION VARCHAR(60) ,
    NUMERIC_CODE DECIMAL(20,0) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`UOM_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `COST_COMPONENT_TYPE`;
CREATE TABLE COST_COMPONENT_TYPE (
    COST_COMPONENT_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`COST_COMPONENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `PERF_REVIEW_ITEM_TYPE`;
CREATE TABLE PERF_REVIEW_ITEM_TYPE (
    PERF_REVIEW_ITEM_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`PERF_REVIEW_ITEM_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `STATUS_TYPE`;
CREATE TABLE STATUS_TYPE (
    STATUS_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`STATUS_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `FIXED_ASSET_IDENT_TYPE`;
CREATE TABLE FIXED_ASSET_IDENT_TYPE (
    FIXED_ASSET_IDENT_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`FIXED_ASSET_IDENT_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `ACCTG_TRANS_ENTRY_TYPE`;
CREATE TABLE ACCTG_TRANS_ENTRY_TYPE (
    ACCTG_TRANS_ENTRY_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`ACCTG_TRANS_ENTRY_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `CUSTOM_SCREEN_TYPE`;
CREATE TABLE CUSTOM_SCREEN_TYPE (
    CUSTOM_SCREEN_TYPE_ID BIGINT auto_increment NOT NULL,
    PARENT_TYPE_ID BIGINT ,
    HAS_TABLE CHAR(1) ,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`CUSTOM_SCREEN_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `JOB_INTERVIEW_TYPE`;
CREATE TABLE JOB_INTERVIEW_TYPE (
    JOB_INTERVIEW_TYPE_ID BIGINT auto_increment NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`JOB_INTERVIEW_TYPE_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `SETTLEMENT_TERM`;
CREATE TABLE SETTLEMENT_TERM (
    SETTLEMENT_TERM_ID BIGINT auto_increment NOT NULL,
    TERM_NAME VARCHAR(100) ,
    TERM_VALUE DECIMAL(20,0) ,
    UOM_ID BIGINT ,
    LAST_UPDATED_STAMP DATETIME(3) ,
    CREATED_STAMP DATETIME(3) ,
    
    PRIMARY KEY (`SETTLEMENT_TERM_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- collect entities 173, from dataset/seed, dataset/common; total 187
