package com.bluecc.hubs.stereotypes;

import com.google.common.collect.ImmutableList;
import java.util.List;
import static com.bluecc.hubs.stereotypes.AccountingSeedData.*;

import com.bluecc.hubs.stub.PeriodTypeData;
import com.bluecc.hubs.stub.ProductAverageCostTypeData;
import com.bluecc.hubs.stub.PartyIdentificationTypeData;
import com.bluecc.hubs.stub.FixedAssetProductTypeData;
import com.bluecc.hubs.stub.RoleTypeData;
import com.bluecc.hubs.stub.AcctgTransTypeData;
import com.bluecc.hubs.stub.CustomMethodData;
import com.bluecc.hubs.stub.GlFiscalTypeData;
import com.bluecc.hubs.stub.InvoiceItemAssocTypeData;
import com.bluecc.hubs.stub.BudgetItemTypeData;
import com.bluecc.hubs.stub.BudgetTypeData;
import com.bluecc.hubs.stub.InvoiceItemTypeMapData;
import com.bluecc.hubs.stub.StatusItemData;
import com.bluecc.hubs.stub.StatusValidChangeData;
import com.bluecc.hubs.stub.GlAccountTypeData;
import com.bluecc.hubs.stub.WorkEffortFlatData;
import com.bluecc.hubs.stub.PaymentGroupTypeData;
import com.bluecc.hubs.stub.GlAccountCategoryTypeData;
import com.bluecc.hubs.stub.FixedAssetStdCostTypeData;
import com.bluecc.hubs.stub.PaymentTypeData;
import com.bluecc.hubs.stub.RateTypeData;
import com.bluecc.hubs.stub.InvoiceItemTypeData;
import com.bluecc.hubs.stub.FinAccountTypeData;
import com.bluecc.hubs.stub.GlResourceTypeData;
import com.bluecc.hubs.stub.InvoiceContentTypeData;
import com.bluecc.hubs.stub.PaymentMethodTypeData;
import com.bluecc.hubs.stub.EnumerationData;
import com.bluecc.hubs.stub.GlAccountClassData;
import com.bluecc.hubs.stub.BudgetReviewResultTypeData;
import com.bluecc.hubs.stub.FinAccountTransTypeData;
import com.bluecc.hubs.stub.EnumerationTypeData;
import com.bluecc.hubs.stub.TaxAuthorityRateTypeData;
import com.bluecc.hubs.stub.GoodIdentificationTypeData;
import com.bluecc.hubs.stub.TaxAuthorityAssocTypeData;
import com.bluecc.hubs.stub.InvoiceTypeData;
import com.bluecc.hubs.stub.GlAccountGroupTypeData;
import com.bluecc.hubs.stub.StatusTypeData;
import com.bluecc.hubs.stub.FixedAssetIdentTypeData;
import com.bluecc.hubs.stub.AcctgTransEntryTypeData;
import com.bluecc.hubs.stub.GlXbrlClassData;
import com.bluecc.hubs.stub.EmplPositionTypeData;
import com.bluecc.hubs.stub.GlAccountGroupData;
import com.bluecc.hubs.stub.CustomMethodTypeData;
import com.bluecc.hubs.stub.CustomScreenTypeData;
import com.bluecc.hubs.stub.FixedAssetTypeData;
import com.bluecc.hubs.stub.PaymentGatewayConfigTypeData;
import com.bluecc.hubs.stub.SettlementTermData;

public final class AccountingSeedDataList {
    public static final List<PeriodTypeData> periodTypeList=ImmutableList.of(        
            PeriodType_RATE_HOUR,        
            PeriodType_RATE_WEEK,        
            PeriodType_RATE_MONTH,        
            PeriodType_RATE_QUARTER);

    public static final List<ProductAverageCostTypeData> productAverageCostTypeList=ImmutableList.of(        
            ProductAverageCostType_SIMPLE_AVG_COST,        
            ProductAverageCostType_WEIGHTED_AVG_COST,        
            ProductAverageCostType_MOVING_AVG_COST);

    public static final List<PartyIdentificationTypeData> partyIdentificationTypeList=ImmutableList.of(        
            PartyIdentificationType_INVOICE_EXPORT);

    public static final List<FixedAssetProductTypeData> fixedAssetProductTypeList=ImmutableList.of(        
            FixedAssetProductType_FAPT_USE,        
            FixedAssetProductType_FAPT_SALE);

    public static final List<RoleTypeData> roleTypeList=ImmutableList.of(        
            RoleType_BUDGET,        
            RoleType_BUDGET_APPL,        
            RoleType_BUDGET_MGR,        
            RoleType_BUDGET_RVR,        
            RoleType_BUDGET_APPRV,        
            RoleType_FAM_ASSIGNEE,        
            RoleType_FAM_SUPPLIER,        
            RoleType_FAM_MANAGER,        
            RoleType_FAM_WORKER);

    public static final List<AcctgTransTypeData> acctgTransTypeList=ImmutableList.of(        
            AcctgTransType__NA_,        
            AcctgTransType_INTERNAL_ACCTG_TRANS,        
            AcctgTransType_AMORTIZATION,        
            AcctgTransType_DEPRECIATION,        
            AcctgTransType_CAPITALIZATION,        
            AcctgTransType_INVENTORY,        
            AcctgTransType_ITEM_VARIANCE,        
            AcctgTransType_OTHER_INTERNAL,        
            AcctgTransType_PERIOD_CLOSING,        
            AcctgTransType_EXTERNAL_ACCTG_TRANS,        
            AcctgTransType_OBLIGATION_ACCTG_TRA,        
            AcctgTransType_CREDIT_LINE,        
            AcctgTransType_CREDIT_MEMO,        
            AcctgTransType_NOTE,        
            AcctgTransType_OTHER_OBLIGATION,        
            AcctgTransType_SALES,        
            AcctgTransType_TAX_DUE,        
            AcctgTransType_PAYMENT_ACCTG_TRANS,        
            AcctgTransType_DISBURSEMENT,        
            AcctgTransType_RECEIPT,        
            AcctgTransType_INVENTORY_RETURN,        
            AcctgTransType_SALES_INVOICE,        
            AcctgTransType_PURCHASE_INVOICE,        
            AcctgTransType_CUST_RTN_INVOICE,        
            AcctgTransType_SALES_SHIPMENT,        
            AcctgTransType_SHIPMENT_RECEIPT,        
            AcctgTransType_MANUFACTURING,        
            AcctgTransType_INCOMING_PAYMENT,        
            AcctgTransType_OUTGOING_PAYMENT,        
            AcctgTransType_PAYMENT_APPL);

    public static final List<CustomMethodData> customMethodList=ImmutableList.of(        
            CustomMethod_CC_AUTH_TEST,        
            CustomMethod_CC_AUTH_CAPTURE_TST,        
            CustomMethod_CC_AUTH_RANDOM_TEST,        
            CustomMethod_CC_AUTH_AIM,        
            CustomMethod_CC_AUTH_CAPTURE_AIM,        
            CustomMethod_CC_AUTH_CLEARCOMMERC,        
            CustomMethod_CC_AUTH_CLEARCOM_REP,        
            CustomMethod_CC_AUTH_CYBERSOURCE,        
            CustomMethod_CC_AUTH_PAYFLOW,        
            CustomMethod_CC_AUTH_PCCHARGE,        
            CustomMethod_CC_AUTH_RITA,        
            CustomMethod_CC_AUTH_RITA_REMOTE,        
            CustomMethod_CC_AUTH_ALWAYSAPPROV,        
            CustomMethod_CC_AUTH_ALWAYSDECLIN,        
            CustomMethod_CC_AUTH_ALWAYSNSF,        
            CustomMethod_CC_AUTH_ALWAYSBAD,        
            CustomMethod_CC_AUTH_ALWAYSEVEN,        
            CustomMethod_CC_AUTH_ALWAYSBADNUM,        
            CustomMethod_CC_AUTH_ALWAYSFAIL,        
            CustomMethod_CC_AUTH_CAPTURE_ALWA,        
            CustomMethod_CC_AUTH_ORBITAL,        
            CustomMethod_CC_AUTH_CAPTR_ORBTL,        
            CustomMethod_CC_CAPTURE_TEST,        
            CustomMethod_CC_CAPTURE_REAUTH,        
            CustomMethod_CC_CAPTURE_ALWAYSDEC,        
            CustomMethod_CC_CAPTURE_AIM,        
            CustomMethod_CC_CAPTURE_CLEARCOMM,        
            CustomMethod_CC_CAPTURE_CYBERSOUR,        
            CustomMethod_CC_CAPTURE_PAYFLOW,        
            CustomMethod_CC_CAPTURE_PCCHARGE,        
            CustomMethod_CC_CAPTURE_RITA,        
            CustomMethod_CC_CAPTURE_RITA_REMO,        
            CustomMethod_CC_CAPTURE_ORBITAL,        
            CustomMethod_CC_REFUND_TEST,        
            CustomMethod_CC_REFUND_TEST_FAIL,        
            CustomMethod_CC_REFUND_AIM,        
            CustomMethod_CC_REFUND_CLEARCOMME,        
            CustomMethod_CC_REFUND_CYBERSOURC,        
            CustomMethod_CC_REFUND_PAYFLOW,        
            CustomMethod_CC_REFUND_PCCHARGE,        
            CustomMethod_CC_REFUND_RITA,        
            CustomMethod_CC_REFUND_RITA_REMOT,        
            CustomMethod_CC_REFUND_ORBITAL,        
            CustomMethod_CC_RELEASE_TEST,        
            CustomMethod_CC_RELEASE_AIM,        
            CustomMethod_CC_RELEASE_CLEARCOMM,        
            CustomMethod_CC_RELEASE_CYBERSOUR,        
            CustomMethod_CC_RELEASE_PAYFLOW,        
            CustomMethod_CC_RELEASE_PCCHARGE,        
            CustomMethod_CC_RELEASE_RITA,        
            CustomMethod_CC_RELEASE_RITA_REMO,        
            CustomMethod_CC_RELEASE_ORBITAL,        
            CustomMethod_CC_CREDIT_AIM,        
            CustomMethod_CC_CREDIT_CLEARCOMME,        
            CustomMethod_CC_CREDIT_CYBERSOURC,        
            CustomMethod_CC_CREDIT_RITA,        
            CustomMethod_EFT_AUTH_TEST,        
            CustomMethod_EFT_AUTH_ALWAYSAPPRO,        
            CustomMethod_EFT_AUTH_ALWAYSDECLI,        
            CustomMethod_EFT_RELEASE_TEST,        
            CustomMethod_FIN_AUTH_OFBIZ,        
            CustomMethod_FIN_CAPTURE_OFBIZ,        
            CustomMethod_FIN_REFUND_OFBIZ,        
            CustomMethod_FIN_RELEASE_OFBIZ,        
            CustomMethod_FIN_PURCH_OFBIZ,        
            CustomMethod_GIFT_AUTH_OFBIZ,        
            CustomMethod_GIFT_AUTH_ALWAYSAPPR,        
            CustomMethod_GIFT_AUTH_ALWAYSDECL,        
            CustomMethod_GIFT_AUTH_VALUELINK,        
            CustomMethod_GIFT_CAPTURE_OFBIZ,        
            CustomMethod_GIFT_REFUND_OFBIZ,        
            CustomMethod_GIFT_REFUND_VALUELI,        
            CustomMethod_GIFT_RELEASE_OFBIZ,        
            CustomMethod_GIFT_RELEASE_TEST,        
            CustomMethod_GIFT_RELEASE_VALUEL,        
            CustomMethod_GIFT_PURCH_OFBIZ,        
            CustomMethod_PAYPAL_AUTH_PFP,        
            CustomMethod_PAYPAL_AUTH,        
            CustomMethod_PAYPAL_CAPTURE_PFP,        
            CustomMethod_PAYPAL_CAPTURE,        
            CustomMethod_PAYPAL_REFUND_PFP,        
            CustomMethod_PAYPAL_REFUND,        
            CustomMethod_PAYPAL_RELEASE_PFP,        
            CustomMethod_PAYPAL_RELEASE,        
            CustomMethod_CC_CHARGE_EWAY,        
            CustomMethod_CC_REFUND_EWAY,        
            CustomMethod_CC_RELEASE_EWAY,        
            CustomMethod_SECURE_AUTH_OFBIZ,        
            CustomMethod_SECURE_CAPTURE_OFBIZ,        
            CustomMethod_SECURE_REFUND_OFBIZ,        
            CustomMethod_SECURE_RELEASE_OFBIZ,        
            CustomMethod_SECURE_CREDIT_OFBIZ,        
            CustomMethod_INV_HOOK_ENF_SEQ,        
            CustomMethod_INV_HOOK_RES_YR,        
            CustomMethod_QUOTE_HOOK_ENF_SEQ,        
            CustomMethod_ORDER_HOOK_ENF_SEQ,        
            CustomMethod_STR_LINE_DEP_FORMULA,        
            CustomMethod_DBL_DECL_DEP_FORMULA);

    public static final List<GlFiscalTypeData> glFiscalTypeList=ImmutableList.of(        
            GlFiscalType_ACTUAL,        
            GlFiscalType_BUDGET,        
            GlFiscalType_FORECAST,        
            GlFiscalType_PLAN,        
            GlFiscalType_SCENARIO);

    public static final List<InvoiceItemAssocTypeData> invoiceItemAssocTypeList=ImmutableList.of(        
            InvoiceItemAssocType_COMMISSION_INVOICE,        
            InvoiceItemAssocType_WITHDRAW_INVOICE);

    public static final List<BudgetItemTypeData> budgetItemTypeList=ImmutableList.of(        
            BudgetItemType_REQUIREMENT_BUDGET_A);

    public static final List<BudgetTypeData> budgetTypeList=ImmutableList.of(        
            BudgetType_CAPITAL_BUDGET,        
            BudgetType_OPERATING_BUDGET);

    public static final List<InvoiceItemTypeMapData> invoiceItemTypeMapList=ImmutableList.of(        
            InvoiceItemTypeMap_FINISHED_GOOD_SALES_INVOICE,        
            InvoiceItemTypeMap_SERVICE_PRODUCT_SALES_INVOICE,        
            InvoiceItemTypeMap_SERVICE_SALES_INVOICE,        
            InvoiceItemTypeMap_DIGITAL_GOOD_SALES_INVOICE,        
            InvoiceItemTypeMap_FINDIG_GOOD_SALES_INVOICE,        
            InvoiceItemTypeMap_PROMOTION_ADJUSTMENT_SALES_INVOICE,        
            InvoiceItemTypeMap_REPLACE_ADJUSTMENT_SALES_INVOICE,        
            InvoiceItemTypeMap_DISCOUNT_ADJUSTMENT_SALES_INVOICE,        
            InvoiceItemTypeMap_FEE_SALES_INVOICE,        
            InvoiceItemTypeMap_MISCELLANEOUS_CHARGE_SALES_INVOICE,        
            InvoiceItemTypeMap_SALES_TAX_SALES_INVOICE,        
            InvoiceItemTypeMap_SHIPPING_CHARGES_SALES_INVOICE,        
            InvoiceItemTypeMap_SURCHARGE_ADJUSTMENT_SALES_INVOICE,        
            InvoiceItemTypeMap_ADDITIONAL_FEATURE_SALES_INVOICE,        
            InvoiceItemTypeMap_WARRANTY_ADJUSTMENT_SALES_INVOICE,        
            InvoiceItemTypeMap_VAT_TAX_SALES_INVOICE,        
            InvoiceItemTypeMap_INVENTORY_ORDER_ITEM_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_SUPPLIES_ORDER_ITEM_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_ASSET_ORDER_ITEM_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_FINISHED_GOOD_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_DIGITAL_GOOD_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_FINDIG_GOOD_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_SERVICE_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_RAW_MATERIAL_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_PROMOTION_ADJUSTMENT_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_REPLACE_ADJUSTMENT_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_DISCOUNT_ADJUSTMENT_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_FEE_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_MISCELLANEOUS_CHARGE_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_SALES_TAX_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_SHIPPING_CHARGES_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_SURCHARGE_ADJUSTMENT_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_ADDITIONAL_FEATURE_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_WARRANTY_ADJUSTMENT_PURCHASE_INVOICE,        
            InvoiceItemTypeMap_RET_FPROD_ITEM_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_DPROD_ITEM_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_FDPROD_ITEM_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_RPROD_ITEM_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_PROMOTION_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_REPLACE_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_DISCOUNT_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_FEE_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_MISC_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_SALES_TAX_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_VAT_TAX_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_VAT_PC_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_SHIPPING_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_SURCHARGE_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_ADD_FEATURE_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_WARRANTY_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_MAN_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_MKTG_PKG_ADJ_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_SPROD_ITEM_CUST_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_FPROD_ITEM_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_DPROD_ITEM_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_FDPROD_ITEM_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_RPROD_ITEM_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_PROMOTION_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_REPLACE_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_DISCOUNT_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_FEE_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_MISC_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_SALES_TAX_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_VAT_TAX_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_VAT_PC_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_SHIPPING_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_SURCHARGE_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_ADD_FEATURE_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_WARRANTY_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_MAN_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_RET_MKTG_PKG_ADJ_PURC_RTN_INVOICE,        
            InvoiceItemTypeMap_COM_COMM_ITEM_COMMISSION_INVOICE,        
            InvoiceItemTypeMap_COM_COMM_ADJ_COMMISSION_INVOICE,        
            InvoiceItemTypeMap_INT_INV_CHRG_INTEREST_INVOICE);

    public static final List<StatusItemData> statusItemList=ImmutableList.of(        
            StatusItem_AES_NOT_RECONCILED,        
            StatusItem_AES_PARTLY_RECON,        
            StatusItem_AES_RECONCILED,        
            StatusItem_FNACT_ACTIVE,        
            StatusItem_FNACT_NEGPENDREPL,        
            StatusItem_FNACT_MANFROZEN,        
            StatusItem_FNACT_CANCELLED,        
            StatusItem_FINACT_TRNS_APPROVED,        
            StatusItem_FINACT_TRNS_CREATED,        
            StatusItem_FINACT_TRNS_CANCELED,        
            StatusItem_FAM_CREATED,        
            StatusItem_FAM_SCHEDULED,        
            StatusItem_FAM_IN_PROCESS,        
            StatusItem_FAM_COMPLETED,        
            StatusItem_FAM_CANCELLED,        
            StatusItem_INVOICE_IN_PROCESS,        
            StatusItem_INVOICE_APPROVED,        
            StatusItem_INVOICE_SENT,        
            StatusItem_INVOICE_RECEIVED,        
            StatusItem_INVOICE_READY,        
            StatusItem_INVOICE_PAID,        
            StatusItem_INVOICE_WRITEOFF,        
            StatusItem_INVOICE_CANCELLED,        
            StatusItem_PMNT_NOT_PAID,        
            StatusItem_PMNT_SENT,        
            StatusItem_PMNT_RECEIVED,        
            StatusItem_PMNT_CONFIRMED,        
            StatusItem_PMNT_CANCELLED,        
            StatusItem_PMNT_VOID,        
            StatusItem_GLREC_CREATED,        
            StatusItem_GLREC_RECONCILED,        
            StatusItem_BG_CREATED,        
            StatusItem_BG_REVIEWED,        
            StatusItem_BG_APPROVED,        
            StatusItem_BG_REJECTED);

    public static final List<StatusValidChangeData> statusValidChangeList=ImmutableList.of(        
            StatusValidChange_FNACT_ACTIVE_FNACT_NEGPENDREPL,        
            StatusValidChange_FNACT_ACTIVE_FNACT_MANFROZEN,        
            StatusValidChange_FNACT_ACTIVE_FNACT_CANCELLED,        
            StatusValidChange_FNACT_NEGPENDREPL_FNACT_ACTIVE,        
            StatusValidChange_FNACT_NEGPENDREPL_FNACT_MANFROZEN,        
            StatusValidChange_FNACT_NEGPENDREPL_FNACT_CANCELLED,        
            StatusValidChange_FNACT_MANFROZEN_FNACT_ACTIVE,        
            StatusValidChange_FNACT_MANFROZEN_FNACT_CANCELLED,        
            StatusValidChange_FINACT_TRNS_CREATED_FINACT_TRNS_APPROVED,        
            StatusValidChange_FINACT_TRNS_CREATED_FINACT_TRNS_CANCELED,        
            StatusValidChange_FINACT_TRNS_APPROVED_FINACT_TRNS_CANCELED,        
            StatusValidChange_FAM_CREATED_FAM_SCHEDULED,        
            StatusValidChange_FAM_CREATED_FAM_IN_PROCESS,        
            StatusValidChange_FAM_CREATED_FAM_CANCELLED,        
            StatusValidChange_FAM_SCHEDULED_FAM_IN_PROCESS,        
            StatusValidChange_FAM_SCHEDULED_FAM_CANCELLED,        
            StatusValidChange_FAM_IN_PROCESS_FAM_COMPLETED,        
            StatusValidChange_INVOICE_IN_PROCESS_INVOICE_READY,        
            StatusValidChange_INVOICE_IN_PROCESS_INVOICE_CANCELLED,        
            StatusValidChange_INVOICE_IN_PROCESS_INVOICE_SENT,        
            StatusValidChange_INVOICE_IN_PROCESS_INVOICE_RECEIVED,        
            StatusValidChange_INVOICE_SENT_INVOICE_APPROVED,        
            StatusValidChange_INVOICE_SENT_INVOICE_READY,        
            StatusValidChange_INVOICE_SENT_INVOICE_RECEIVED,        
            StatusValidChange_INVOICE_RECEIVED_INVOICE_READY,        
            StatusValidChange_INVOICE_SENT_INVOICE_CANCELLED,        
            StatusValidChange_INVOICE_RECEIVED_INVOICE_CANCELLED,        
            StatusValidChange_INVOICE_SENT_INVOICE_IN_PROCESS,        
            StatusValidChange_INVOICE_RECEIVED_INVOICE_IN_PROCESS,        
            StatusValidChange_INVOICE_IN_PROCESS_INVOICE_APPROVED,        
            StatusValidChange_INVOICE_APPROVED_INVOICE_SENT,        
            StatusValidChange_INVOICE_RECEIVED_INVOICE_APPROVED,        
            StatusValidChange_INVOICE_APPROVED_INVOICE_READY,        
            StatusValidChange_INVOICE_APPROVED_INVOICE_CANCELLED,        
            StatusValidChange_INVOICE_READY_INVOICE_PAID,        
            StatusValidChange_INVOICE_READY_INVOICE_WRITEOFF,        
            StatusValidChange_INVOICE_PAID_INVOICE_READY,        
            StatusValidChange_INVOICE_READY_INVOICE_CANCELLED,        
            StatusValidChange_INVOICE_PAID_INVOICE_CANCELLED,        
            StatusValidChange_PMNT_NOT_PAID_PMNT_SENT,        
            StatusValidChange_PMNT_NOT_PAID_PMNT_RECEIVED,        
            StatusValidChange_PMNT_NOT_PAID_PMNT_CANCELLED,        
            StatusValidChange_PMNT_SENT_PMNT_CONFIRMED,        
            StatusValidChange_PMNT_RECEIVED_PMNT_CONFIRMED,        
            StatusValidChange_PMNT_SENT_PMNT_VOID,        
            StatusValidChange_PMNT_RECEIVED_PMNT_VOID,        
            StatusValidChange_PMNT_NOT_PAID_PMNT_VOID,        
            StatusValidChange_PMNT_SENT_PMNT_NOT_PAID,        
            StatusValidChange_PMNT_RECEIVED_PMNT_NOT_PAID,        
            StatusValidChange_PMNT_CONFIRMED_PMNT_SENT,        
            StatusValidChange_PMNT_CONFIRMED_PMNT_RECEIVED,        
            StatusValidChange_GLREC_CREATED_GLREC_RECONCILED,        
            StatusValidChange_BG_CREATED_BG_REVIEWED,        
            StatusValidChange_BG_CREATED_BG_APPROVED,        
            StatusValidChange_BG_CREATED_BG_REJECTED,        
            StatusValidChange_BG_REVIEWED_BG_APPROVED,        
            StatusValidChange_BG_REVIEWED_BG_REJECTED,        
            StatusValidChange_BG_APPROVED_BG_CREATED,        
            StatusValidChange_BG_APPROVED_BG_REJECTED);

    public static final List<GlAccountTypeData> glAccountTypeList=ImmutableList.of(        
            GlAccountType__NA_,        
            GlAccountType_ACCOUNTS_RECEIVABLE,        
            GlAccountType_ACCOUNTS_PAYABLE,        
            GlAccountType_BALANCE_ACCOUNT,        
            GlAccountType_BANK_STLMNT_ACCOUNT,        
            GlAccountType_UNDEPOSITED_RECEIPTS,        
            GlAccountType_MRCH_STLMNT_ACCOUNT,        
            GlAccountType_CURRENT_ASSET,        
            GlAccountType_FIXED_ASSET,        
            GlAccountType_FIXED_ASSET_MAINT,        
            GlAccountType_OTHER_ASSET,        
            GlAccountType_CREDIT_CARD,        
            GlAccountType_CURRENT_LIABILITY,        
            GlAccountType_LONG_TERM_LIABILITY,        
            GlAccountType_CUSTOMER_ACCOUNT,        
            GlAccountType_SUPPLIER_ACCOUNT,        
            GlAccountType_PRODUCT_ACCOUNT,        
            GlAccountType_INVENTORY_ACCOUNT,        
            GlAccountType_INV_ADJ_AVG_COST,        
            GlAccountType_INV_ADJ_VAL,        
            GlAccountType_RAWMAT_INVENTORY,        
            GlAccountType_WIP_INVENTORY,        
            GlAccountType_TAX_ACCOUNT,        
            GlAccountType_PROFIT_LOSS_ACCOUNT,        
            GlAccountType_SALES_ACCOUNT,        
            GlAccountType_SALES_RETURNS,        
            GlAccountType_DISCOUNTS_ACCOUNT,        
            GlAccountType_COGS_ACCOUNT,        
            GlAccountType_COGS_ADJ_AVG_COST,        
            GlAccountType_PURCHASE_ACCOUNT,        
            GlAccountType_INV_CHANGE_ACCOUNT,        
            GlAccountType_EXPENSE,        
            GlAccountType_OPERATING_EXPENSE,        
            GlAccountType_OTHER_EXPENSE,        
            GlAccountType_OWNERS_EQUITY,        
            GlAccountType_RETAINED_EARNINGS,        
            GlAccountType_CUSTOMER_DEPOSIT,        
            GlAccountType_CUSTOMER_CREDIT,        
            GlAccountType_CUSTOMER_GC_DEPOSIT,        
            GlAccountType_UNINVOICED_SHIP_RCPT,        
            GlAccountType_PURCHASE_PRICE_VAR,        
            GlAccountType_INCOME,        
            GlAccountType_OTHER_INCOME,        
            GlAccountType_INTEREST_INCOME,        
            GlAccountType_INTRSTINC_RECEIVABLE,        
            GlAccountType_PREPAID_EXPENSES,        
            GlAccountType_INVENTORY_XFER_OUT,        
            GlAccountType_INVENTORY_XFER_IN,        
            GlAccountType_ACCPAYABLE_UNAPPLIED,        
            GlAccountType_ACCREC_UNAPPLIED,        
            GlAccountType_COMMISSION_EXPENSE,        
            GlAccountType_COMMISSIONS_PAYABLE,        
            GlAccountType_WRITEOFF,        
            GlAccountType_ACCTRECV_WRITEOFF,        
            GlAccountType_ACCTPAY_WRITEOFF,        
            GlAccountType_COMMISSIONS_WRITEOFF,        
            GlAccountType_INTRSTINC_WRITEOFF,        
            GlAccountType_FX_GAIN_LOSS_ACCT,        
            GlAccountType_FX_GAIN_ACCOUNT,        
            GlAccountType_FX_LOSS_ACCOUNT);

    public static final List<WorkEffortFlatData> workEffortList=ImmutableList.of(        
            WorkEffort__NA_);

    public static final List<PaymentGroupTypeData> paymentGroupTypeList=ImmutableList.of(        
            PaymentGroupType_CHECK_RUN,        
            PaymentGroupType_BATCH_PAYMENT);

    public static final List<GlAccountCategoryTypeData> glAccountCategoryTypeList=ImmutableList.of(        
            GlAccountCategoryType_COST_CENTER);

    public static final List<FixedAssetStdCostTypeData> fixedAssetStdCostTypeList=ImmutableList.of(        
            FixedAssetStdCostType_SETUP_COST,        
            FixedAssetStdCostType_USAGE_COST);

    public static final List<PaymentTypeData> paymentTypeList=ImmutableList.of(        
            PaymentType_DISBURSEMENT,        
            PaymentType_CUSTOMER_REFUND,        
            PaymentType_VENDOR_PAYMENT,        
            PaymentType_VENDOR_PREPAY,        
            PaymentType_COMMISSION_PAYMENT,        
            PaymentType_PAYROL_PAYMENT,        
            PaymentType_PAY_CHECK,        
            PaymentType_TAX_PAYMENT,        
            PaymentType_SALES_TAX_PAYMENT,        
            PaymentType_PAYROLL_TAX_PAYMENT,        
            PaymentType_INCOME_TAX_PAYMENT,        
            PaymentType_GC_WITHDRAWAL,        
            PaymentType_RECEIPT,        
            PaymentType_CUSTOMER_PAYMENT,        
            PaymentType_CUSTOMER_DEPOSIT,        
            PaymentType_INTEREST_RECEIPT,        
            PaymentType_GC_DEPOSIT);

    public static final List<RateTypeData> rateTypeList=ImmutableList.of(        
            RateType_STANDARD,        
            RateType_DISCOUNTED,        
            RateType_OVERTIME,        
            RateType_AVERAGE_PAY_RATE,        
            RateType_HIGH_PAY_RATE,        
            RateType_LOW_PAY_RATE);

    public static final List<InvoiceItemTypeData> invoiceItemTypeList=ImmutableList.of(        
            InvoiceItemType_INVOICE_ADJ,        
            InvoiceItemType_INVOICE_HEAD_ADJ,        
            InvoiceItemType_INVOICE_ITM_ADJ,        
            InvoiceItemType_SINVOICE_HEAD_ADJ,        
            InvoiceItemType_SINVOICE_ITM_ADJ,        
            InvoiceItemType_PINVOICE_ADJ,        
            InvoiceItemType_PINVOICE_ITM_ADJ,        
            InvoiceItemType_CRETURN_ADJ,        
            InvoiceItemType_SRETURN_ADJ,        
            InvoiceItemType_INV_PROMOTION_ADJ,        
            InvoiceItemType_INV_DISCOUNT_ADJ,        
            InvoiceItemType_FEE,        
            InvoiceItemType_INV_MISC_CHARGE,        
            InvoiceItemType_INV_SALES_TAX,        
            InvoiceItemType_INV_SHIPPING_CHARGES,        
            InvoiceItemType_INV_SURCHARGE_ADJ,        
            InvoiceItemType_INV_ADD_FEATURE,        
            InvoiceItemType_INV_WARRANTY_ADJ,        
            InvoiceItemType_INV_INTRST_CHRG,        
            InvoiceItemType_ITM_PROMOTION_ADJ,        
            InvoiceItemType_ITM_REPLACE_ADJ,        
            InvoiceItemType_ITM_DISCOUNT_ADJ,        
            InvoiceItemType_ITM_FEE,        
            InvoiceItemType_ITM_MISC_CHARGE,        
            InvoiceItemType_ITM_SALES_TAX,        
            InvoiceItemType_ITM_SHIPPING_CHARGES,        
            InvoiceItemType_ITM_SURCHARGE_ADJ,        
            InvoiceItemType_ITM_ADD_FEATURE,        
            InvoiceItemType_ITM_WARRANTY_ADJ,        
            InvoiceItemType_ITM_VAT_TAX,        
            InvoiceItemType_INV_PROD_ITEM,        
            InvoiceItemType_INV_FPROD_ITEM,        
            InvoiceItemType_INV_DPROD_ITEM,        
            InvoiceItemType_INV_FDPROD_ITEM,        
            InvoiceItemType_INV_PROD_FEATR_ITEM,        
            InvoiceItemType_INV_SPROD_ITEM,        
            InvoiceItemType_INV_WE_ITEM,        
            InvoiceItemType_INV_TE_ITEM,        
            InvoiceItemType_PINV_PROMOTION_ADJ,        
            InvoiceItemType_PINV_DISCOUNT_ADJ,        
            InvoiceItemType_P_FEE,        
            InvoiceItemType_PINV_MISC_CHARGE,        
            InvoiceItemType_PINV_SALES_TAX,        
            InvoiceItemType_PINV_SHIP_CHARGES,        
            InvoiceItemType_PINV_SURCHARGE_ADJ,        
            InvoiceItemType_PINV_ADD_FEATURE,        
            InvoiceItemType_PINV_WARRANTY_ADJ,        
            InvoiceItemType_PITM_PROMOTION_ADJ,        
            InvoiceItemType_PITM_REPLACE_ADJ,        
            InvoiceItemType_PITM_DISCOUNT_ADJ,        
            InvoiceItemType_PITM_FEE,        
            InvoiceItemType_PITM_MISC_CHARGE,        
            InvoiceItemType_PITM_SALES_TAX,        
            InvoiceItemType_PITM_SHIP_CHARGES,        
            InvoiceItemType_PITM_SURCHARGE_ADJ,        
            InvoiceItemType_PITM_ADD_FEATURE,        
            InvoiceItemType_PITM_WARRANTY_ADJ,        
            InvoiceItemType_PINV_PROD_ITEM,        
            InvoiceItemType_PINV_FPROD_ITEM,        
            InvoiceItemType_PINV_DPROD_ITEM,        
            InvoiceItemType_PINV_FDPROD_ITEM,        
            InvoiceItemType_PINV_PROD_FEATR_ITEM,        
            InvoiceItemType_PINV_RPROD_ITEM,        
            InvoiceItemType_PINV_SPROD_ITEM,        
            InvoiceItemType_PINV_INVPRD_ITEM,        
            InvoiceItemType_PINV_SUPLPRD_ITEM,        
            InvoiceItemType_PINV_FXASTPRD_ITEM,        
            InvoiceItemType_PINV_WE_ITEM,        
            InvoiceItemType_PINV_TE_ITEM,        
            InvoiceItemType_CRT_PROD_ITEM,        
            InvoiceItemType_CRT_FPROD_ITEM,        
            InvoiceItemType_CRT_DPROD_ITEM,        
            InvoiceItemType_CRT_FDPROD_ITEM,        
            InvoiceItemType_CRT_RPROD_ITEM,        
            InvoiceItemType_CRT_PROD_FEATR_ITEM,        
            InvoiceItemType_CRT_SPROD_ITEM,        
            InvoiceItemType_CRT_WE_ITEM,        
            InvoiceItemType_CRT_TE_ITEM,        
            InvoiceItemType_CRT_PROMOTION_ADJ,        
            InvoiceItemType_CRT_REPLACE_ADJ,        
            InvoiceItemType_CRT_DISCOUNT_ADJ,        
            InvoiceItemType_CRT_FEE_ADJ,        
            InvoiceItemType_CRT_MISC_ADJ,        
            InvoiceItemType_CRT_SALES_TAX_ADJ,        
            InvoiceItemType_CRT_VAT_TAX_ADJ,        
            InvoiceItemType_CRT_VAT_PC_ADJ,        
            InvoiceItemType_CRT_SHIPPING_ADJ,        
            InvoiceItemType_CRT_SURCHARGE_ADJ,        
            InvoiceItemType_CRT_ADD_FEATURE_ADJ,        
            InvoiceItemType_CRT_WARRANTY_ADJ,        
            InvoiceItemType_CRT_MKTG_PKG_ADJ,        
            InvoiceItemType_CRT_MAN_ADJ,        
            InvoiceItemType_SRT_PROD_ITEM,        
            InvoiceItemType_SRT_FPROD_ITEM,        
            InvoiceItemType_SRT_DPROD_ITEM,        
            InvoiceItemType_SRT_FDPROD_ITEM,        
            InvoiceItemType_SRT_RPROD_ITEM,        
            InvoiceItemType_SRT_PROD_FEATR_ITEM,        
            InvoiceItemType_SRT_SPROD_ITEM,        
            InvoiceItemType_SRT_WE_ITEM,        
            InvoiceItemType_SRT_TE_ITEM,        
            InvoiceItemType_SRT_PROMOTION_ADJ,        
            InvoiceItemType_SRT_REPLACE_ADJ,        
            InvoiceItemType_SRT_DISCOUNT_ADJ,        
            InvoiceItemType_SRT_FEE_ADJ,        
            InvoiceItemType_SRT_MISC_ADJ,        
            InvoiceItemType_SRT_SALES_TAX_ADJ,        
            InvoiceItemType_SRT_VAT_TAX_ADJ,        
            InvoiceItemType_SRT_VAT_PC_ADJ,        
            InvoiceItemType_SRT_SHIPPING_ADJ,        
            InvoiceItemType_SRT_SURCHARGE_ADJ,        
            InvoiceItemType_SRT_ADD_FEATURE_ADJ,        
            InvoiceItemType_SRT_WARRANTY_ADJ,        
            InvoiceItemType_SRT_MKTG_PKG_ADJ,        
            InvoiceItemType_SRT_MAN_ADJ,        
            InvoiceItemType_COMM_INV_ITEM,        
            InvoiceItemType_COMM_INV_ADJ,        
            InvoiceItemType_PAYROL,        
            InvoiceItemType_PAYROL_EARN_HOURS,        
            InvoiceItemType_PAYROL_HRLY_RATE,        
            InvoiceItemType_PAYROL_HRLY_RATE_SIC,        
            InvoiceItemType_PAYROL_SALARY,        
            InvoiceItemType_PAYROL_SALARY_VAC,        
            InvoiceItemType_PAYROL_SALARY_SICK,        
            InvoiceItemType_PAYROL_BONUS,        
            InvoiceItemType_PAYROL_COMMISSION,        
            InvoiceItemType_PAYROL_ADV_PAY,        
            InvoiceItemType_PAYROL_MIL_REIMB,        
            InvoiceItemType_PAYROL_OFF_EXP_REIMB,        
            InvoiceItemType_PAYROL_PAYPER_OVRPAY,        
            InvoiceItemType_PAYROL_PAYPER_PAY,        
            InvoiceItemType_PAYROL_DD_FROM_GROSS,        
            InvoiceItemType_PAYROL_DD_125COMPY,        
            InvoiceItemType_PAYROL_DD_125PPO,        
            InvoiceItemType_PAYROL_DD_125HSA,        
            InvoiceItemType_PAYROL_DD_401K,        
            InvoiceItemType_PAYROL_DD_REPAY,        
            InvoiceItemType_PAYROL_DD_CHAR_DONAT,        
            InvoiceItemType_PAYROL_DD_CHILD_SUPP,        
            InvoiceItemType_PAYROL_DD_MISC,        
            InvoiceItemType_PAYROL_DD_ROTH_401K,        
            InvoiceItemType_PAYROL_DD_SIMP_IRA,        
            InvoiceItemType_PAYROL_DD_UNION,        
            InvoiceItemType_PAYROL_DD_SAL_TIMOFF,        
            InvoiceItemType_PAYROL_DD_WAG_GARN,        
            InvoiceItemType_PAYROL_TAXES,        
            InvoiceItemType_PAYROL_TAX_FEDERAL,        
            InvoiceItemType_PAYROL_SOC_SEC_EMPL,        
            InvoiceItemType_PAYROL_TAX_MED_EMPL,        
            InvoiceItemType_PAYROL_TAX_MD_WITHOL);

    public static final List<FinAccountTypeData> finAccountTypeList=ImmutableList.of(        
            FinAccountType_GIFTCERT_ACCOUNT,        
            FinAccountType_DEPOSIT_ACCOUNT,        
            FinAccountType_BANK_ACCOUNT,        
            FinAccountType_STORE_CREDIT_ACCT,        
            FinAccountType_INVESTMENT_ACCOUNT,        
            FinAccountType_REPLENISH_ACCOUNT,        
            FinAccountType_SVCCRED_ACCOUNT,        
            FinAccountType_LOAN_ACCOUNT,        
            FinAccountType_CREDIT_CARD_ACCOUNT,        
            FinAccountType_EQUITY_LINE_ACCOUNT);

    public static final List<GlResourceTypeData> glResourceTypeList=ImmutableList.of(        
            GlResourceType__NA_,        
            GlResourceType_MONEY,        
            GlResourceType_RAW_MATERIALS,        
            GlResourceType_LABOR,        
            GlResourceType_SERVICES,        
            GlResourceType_FINISHED_GOODS,        
            GlResourceType_DELIVERED_GOODS);

    public static final List<InvoiceContentTypeData> invoiceContentTypeList=ImmutableList.of(        
            InvoiceContentType_COMMENTS);

    public static final List<PaymentMethodTypeData> paymentMethodTypeList=ImmutableList.of(        
            PaymentMethodType_CREDIT_CARD,        
            PaymentMethodType_GIFT_CARD,        
            PaymentMethodType_GIFT_CERTIFICATE,        
            PaymentMethodType_CASH,        
            PaymentMethodType_EFT_ACCOUNT,        
            PaymentMethodType_FIN_ACCOUNT,        
            PaymentMethodType_PERSONAL_CHECK,        
            PaymentMethodType_COMPANY_CHECK,        
            PaymentMethodType_CERTIFIED_CHECK,        
            PaymentMethodType_MONEY_ORDER,        
            PaymentMethodType_COMPANY_ACCOUNT,        
            PaymentMethodType_EXT_BILLACT,        
            PaymentMethodType_EXT_COD,        
            PaymentMethodType_EXT_EBAY,        
            PaymentMethodType_EXT_OFFLINE,        
            PaymentMethodType_EXT_PAYPAL,        
            PaymentMethodType_EXT_WORLDPAY);

    public static final List<EnumerationData> enumerationList=ImmutableList.of(        
            Enumeration_GC_ACTIVATE,        
            Enumeration_GC_RELOAD,        
            Enumeration_PGT_AUTHORIZE,        
            Enumeration_PGT_CAPTURE,        
            Enumeration_PGT_RELEASE,        
            Enumeration_PGT_REFUND,        
            Enumeration_PGT_CREDIT,        
            Enumeration_FARP_AUTOMATIC,        
            Enumeration_FARP_MANUAL,        
            Enumeration_FARP_NONE,        
            Enumeration_FARP_TOP_OFF,        
            Enumeration_FARP_REPLENISH_LEVEL,        
            Enumeration_FATR_PURCHASE,        
            Enumeration_FATR_IDEPOSIT,        
            Enumeration_FATR_REPLENISH,        
            Enumeration_FATR_REFUND,        
            Enumeration_FAC_BOAT,        
            Enumeration_FAC_FORKLIFT,        
            Enumeration_FAC_DIGGER,        
            Enumeration_FAC_MANLIFT,        
            Enumeration_FAC_SERVICE_BODY,        
            Enumeration_FAC_TRACTOR,        
            Enumeration_FAC_PASSENGER,        
            Enumeration_FAC_COMPRESSOR,        
            Enumeration_FAC_TRENCHER,        
            Enumeration_FAC_PULLER,        
            Enumeration_FAC_MOBILE,        
            Enumeration_FAC_TANKER,        
            Enumeration_FAC_REEL_STAND,        
            Enumeration_FAC_DESKTOP,        
            Enumeration_FAC_LAPTOP,        
            Enumeration_FAC_MONITOR,        
            Enumeration_FAC_PRG_SOFTWARE,        
            Enumeration_FAC_SYS_SOFTWARE,        
            Enumeration_FAC_APP_SOFTWARE,        
            Enumeration_FAC_UTIL_SOFTWARE,        
            Enumeration_INV_SALES_TAX,        
            Enumeration_ITM_SALES_TAX,        
            Enumeration_PINV_SALES_TAX,        
            Enumeration_PITM_SALES_TAX,        
            Enumeration_CRT_SALES_TAX_ADJ,        
            Enumeration_CCT_VISA,        
            Enumeration_CCT_MASTERCARD,        
            Enumeration_CCT_AMERICANEXPRESS,        
            Enumeration_CCT_DINERSCLUB,        
            Enumeration_CCT_DISCOVER,        
            Enumeration_CCT_ENROUTE,        
            Enumeration_CCT_CARTEBLANCHE,        
            Enumeration_CCT_JCB,        
            Enumeration_CCT_SOLO,        
            Enumeration_CCT_SWITCH,        
            Enumeration_CCT_VISAELECTRON,        
            Enumeration_CCT_UATP,        
            Enumeration_US_IRS_1120,        
            Enumeration_US_IRS_1120S,        
            Enumeration_US_IRS_1065,        
            Enumeration_US_IRS_990,        
            Enumeration_US_IRS_990PF,        
            Enumeration_US_IRS_990T,        
            Enumeration_US_IRS_1040,        
            Enumeration_COGS_LIFO,        
            Enumeration_COGS_FIFO,        
            Enumeration_COGS_AVG_COST,        
            Enumeration_COGS_INV_COST,        
            Enumeration_INVSQ_STANDARD,        
            Enumeration_INVSQ_ENF_SEQ,        
            Enumeration_INVSQ_RESTARTYR,        
            Enumeration_QTESQ_STANDARD,        
            Enumeration_QTESQ_ENF_SEQ,        
            Enumeration_ODRSQ_STANDARD,        
            Enumeration_ODRSQ_ENF_SEQ,        
            Enumeration_POTT_DEST,        
            Enumeration_POTT_ORIG,        
            Enumeration_POTT_INTR,        
            Enumeration_POTT_EXW,        
            Enumeration_POTT_FOB,        
            Enumeration_POTT_FCA,        
            Enumeration_POTT_FAS,        
            Enumeration_POTT_CFR,        
            Enumeration_POTT_CIF,        
            Enumeration_POTT_CPT,        
            Enumeration_POTT_CIP,        
            Enumeration_POTT_DAF,        
            Enumeration_POTT_DES,        
            Enumeration_POTT_DEQ,        
            Enumeration_POTT_DDP,        
            Enumeration_POTT_DDQ,        
            Enumeration_FIN_ACCOUNT,        
            Enumeration_BILLING_ACCOUNT);

    public static final List<GlAccountClassData> glAccountClassList=ImmutableList.of(        
            GlAccountClass_DEBIT,        
            GlAccountClass_CREDIT,        
            GlAccountClass_RESOURCE,        
            GlAccountClass_ASSET,        
            GlAccountClass_DISTRIBUTION,        
            GlAccountClass_EXPENSE,        
            GlAccountClass_CONTRA_REVENUE,        
            GlAccountClass_NON_POSTING,        
            GlAccountClass_LIABILITY,        
            GlAccountClass_EQUITY,        
            GlAccountClass_REVENUE,        
            GlAccountClass_CONTRA_ASSET,        
            GlAccountClass_INCOME,        
            GlAccountClass_CURRENT_ASSET,        
            GlAccountClass_LONGTERM_ASSET,        
            GlAccountClass_CASH_EQUIVALENT,        
            GlAccountClass_INVENTORY_ASSET,        
            GlAccountClass_RETURN_OF_CAPITAL,        
            GlAccountClass_DIVIDEND,        
            GlAccountClass_CASH_EXPENSE,        
            GlAccountClass_NON_CASH_EXPENSE,        
            GlAccountClass_INTEREST_EXPENSE,        
            GlAccountClass_COGS_EXPENSE,        
            GlAccountClass_SGA_EXPENSE,        
            GlAccountClass_DEPRECIATION,        
            GlAccountClass_AMORTIZATION,        
            GlAccountClass_INVENTORY_ADJUST,        
            GlAccountClass_CURRENT_LIABILITY,        
            GlAccountClass_LONGTERM_LIABILITY,        
            GlAccountClass_OWNERS_EQUITY,        
            GlAccountClass_RETAINED_EARNINGS,        
            GlAccountClass_ACCUM_DEPRECIATION,        
            GlAccountClass_ACCUM_AMORTIZATION,        
            GlAccountClass_CASH_INCOME,        
            GlAccountClass_NON_CASH_INCOME);

    public static final List<BudgetReviewResultTypeData> budgetReviewResultTypeList=ImmutableList.of(        
            BudgetReviewResultType_BGR_ACCEPTED,        
            BudgetReviewResultType_BGR_REJECTED);

    public static final List<FinAccountTransTypeData> finAccountTransTypeList=ImmutableList.of(        
            FinAccountTransType_DEPOSIT,        
            FinAccountTransType_WITHDRAWAL,        
            FinAccountTransType_ADJUSTMENT);

    public static final List<EnumerationTypeData> enumerationTypeList=ImmutableList.of(        
            EnumerationType_GC_FULFILL,        
            EnumerationType_PGT_CODE,        
            EnumerationType_FARP_TYPE,        
            EnumerationType_FARP_METHOD,        
            EnumerationType_FINACCT_TRANS_REASON,        
            EnumerationType_FXAST_CLASS,        
            EnumerationType_FXAST_COMPU_HARDWARE,        
            EnumerationType_FXAST_COMPU_SOFTWARE,        
            EnumerationType_TAXABLE_INV_ITM_TY,        
            EnumerationType_CREDIT_CARD_TYPE,        
            EnumerationType_TAX_FORMS,        
            EnumerationType_COGS_METHODS,        
            EnumerationType_INVOICE_SEQMD,        
            EnumerationType_QUOTE_SEQMD,        
            EnumerationType_ORDER_SEQMD,        
            EnumerationType_PTSOFTTFR,        
            EnumerationType_STR_CRDT_ACT);

    public static final List<TaxAuthorityRateTypeData> taxAuthorityRateTypeList=ImmutableList.of(        
            TaxAuthorityRateType_SALES_TAX,        
            TaxAuthorityRateType_USE_TAX,        
            TaxAuthorityRateType_INCOME_TAX,        
            TaxAuthorityRateType_EXPORT_TAX,        
            TaxAuthorityRateType_IMPORT_TAX,        
            TaxAuthorityRateType_VAT_TAX);

    public static final List<GoodIdentificationTypeData> goodIdentificationTypeList=ImmutableList.of(        
            GoodIdentificationType_INVOICE_EXPORT);

    public static final List<TaxAuthorityAssocTypeData> taxAuthorityAssocTypeList=ImmutableList.of(        
            TaxAuthorityAssocType_EXEMPT_INHER,        
            TaxAuthorityAssocType_COLLECT_AGENT);

    public static final List<InvoiceTypeData> invoiceTypeList=ImmutableList.of(        
            InvoiceType_INVOICE,        
            InvoiceType_PURCHASE_INVOICE,        
            InvoiceType_SALES_INVOICE,        
            InvoiceType_CUST_RTN_INVOICE,        
            InvoiceType_PURC_RTN_INVOICE,        
            InvoiceType_COMMISSION_INVOICE,        
            InvoiceType_INTEREST_INVOICE,        
            InvoiceType_TEMPLATE,        
            InvoiceType_SALES_INV_TEMPLATE,        
            InvoiceType_PUR_INV_TEMPLATE,        
            InvoiceType_PAYROL_INVOICE);

    public static final List<GlAccountGroupTypeData> glAccountGroupTypeList=ImmutableList.of(        
            GlAccountGroupType_TAX_FIELD_US);

    public static final List<StatusTypeData> statusTypeList=ImmutableList.of(        
            StatusType_ACCTG_ENREC_STATUS,        
            StatusType_FINACCT_STATUS,        
            StatusType_FINACT_TRNS_STATUS,        
            StatusType_FIXEDAST_MNT_STATUS,        
            StatusType_BUDGET_STATUS,        
            StatusType_PARTY_ASSET_STATUS,        
            StatusType_INVOICE_STATUS,        
            StatusType_PMNT_STATUS,        
            StatusType_GLREC_STATUS);

    public static final List<FixedAssetIdentTypeData> fixedAssetIdentTypeList=ImmutableList.of(        
            FixedAssetIdentType_MFG_SERIAL,        
            FixedAssetIdentType_TRACKING_VENDOR,        
            FixedAssetIdentType_TRACKING_LABEL,        
            FixedAssetIdentType_VIN,        
            FixedAssetIdentType_GAS_CARD1,        
            FixedAssetIdentType_GAS_CARD2,        
            FixedAssetIdentType_GAS_CARD3);

    public static final List<AcctgTransEntryTypeData> acctgTransEntryTypeList=ImmutableList.of(        
            AcctgTransEntryType__NA_);

    public static final List<GlXbrlClassData> glXbrlClassList=ImmutableList.of(        
            GlXbrlClass_US_GAAP,        
            GlXbrlClass_IAS);

    public static final List<EmplPositionTypeData> emplPositionTypeList=ImmutableList.of(        
            EmplPositionType__NA_);

    public static final List<GlAccountGroupData> glAccountGroupList=ImmutableList.of(        
            GlAccountGroup_9001,        
            GlAccountGroup_9002,        
            GlAccountGroup_9003,        
            GlAccountGroup_9004,        
            GlAccountGroup_9005,        
            GlAccountGroup_9006,        
            GlAccountGroup_9007,        
            GlAccountGroup_9008,        
            GlAccountGroup_9009,        
            GlAccountGroup_9010,        
            GlAccountGroup_9021,        
            GlAccountGroup_9022,        
            GlAccountGroup_9031,        
            GlAccountGroup_9032,        
            GlAccountGroup_9033,        
            GlAccountGroup_9034,        
            GlAccountGroup_9035,        
            GlAccountGroup_9036,        
            GlAccountGroup_9037,        
            GlAccountGroup_9038,        
            GlAccountGroup_9039,        
            GlAccountGroup_9040,        
            GlAccountGroup_9041,        
            GlAccountGroup_9042,        
            GlAccountGroup_9043,        
            GlAccountGroup_9044,        
            GlAccountGroup_9045,        
            GlAccountGroup_9046,        
            GlAccountGroup_9047,        
            GlAccountGroup_9048,        
            GlAccountGroup_9049,        
            GlAccountGroup_9050,        
            GlAccountGroup_9051,        
            GlAccountGroup_9052,        
            GlAccountGroup_9053,        
            GlAccountGroup_9054,        
            GlAccountGroup_9055,        
            GlAccountGroup_9056,        
            GlAccountGroup_9057,        
            GlAccountGroup_9058,        
            GlAccountGroup_9059,        
            GlAccountGroup_9071,        
            GlAccountGroup_9072,        
            GlAccountGroup_9073,        
            GlAccountGroup_9074,        
            GlAccountGroup_9075,        
            GlAccountGroup_9076,        
            GlAccountGroup_9077,        
            GlAccountGroup_9078,        
            GlAccountGroup_9079,        
            GlAccountGroup_9080,        
            GlAccountGroup_9081,        
            GlAccountGroup_9082,        
            GlAccountGroup_9083,        
            GlAccountGroup_9084,        
            GlAccountGroup_9085,        
            GlAccountGroup_9086,        
            GlAccountGroup_9101,        
            GlAccountGroup_9102,        
            GlAccountGroup_9103,        
            GlAccountGroup_9104,        
            GlAccountGroup_9105,        
            GlAccountGroup_9106,        
            GlAccountGroup_9107,        
            GlAccountGroup_9108,        
            GlAccountGroup_9109,        
            GlAccountGroup_9110,        
            GlAccountGroup_9111,        
            GlAccountGroup_9112,        
            GlAccountGroup_9113,        
            GlAccountGroup_9114,        
            GlAccountGroup_9115,        
            GlAccountGroup_9116,        
            GlAccountGroup_9117,        
            GlAccountGroup_9118,        
            GlAccountGroup_9119,        
            GlAccountGroup_9120,        
            GlAccountGroup_9121,        
            GlAccountGroup_9122,        
            GlAccountGroup_9123,        
            GlAccountGroup_9124,        
            GlAccountGroup_9125,        
            GlAccountGroup_9126,        
            GlAccountGroup_9127,        
            GlAccountGroup_9128,        
            GlAccountGroup_9129,        
            GlAccountGroup_9130,        
            GlAccountGroup_9131,        
            GlAccountGroup_9132,        
            GlAccountGroup_9133,        
            GlAccountGroup_9134,        
            GlAccountGroup_9135,        
            GlAccountGroup_9151,        
            GlAccountGroup_9152,        
            GlAccountGroup_9153,        
            GlAccountGroup_9154,        
            GlAccountGroup_9155,        
            GlAccountGroup_9156,        
            GlAccountGroup_9157,        
            GlAccountGroup_9158,        
            GlAccountGroup_9159,        
            GlAccountGroup_9160,        
            GlAccountGroup_9161,        
            GlAccountGroup_9162,        
            GlAccountGroup_9163,        
            GlAccountGroup_9164,        
            GlAccountGroup_9165,        
            GlAccountGroup_9201,        
            GlAccountGroup_9202,        
            GlAccountGroup_9203,        
            GlAccountGroup_9204,        
            GlAccountGroup_9205,        
            GlAccountGroup_9206,        
            GlAccountGroup_9207,        
            GlAccountGroup_9208,        
            GlAccountGroup_9209,        
            GlAccountGroup_9210,        
            GlAccountGroup_9401,        
            GlAccountGroup_9402,        
            GlAccountGroup_9403,        
            GlAccountGroup_9404,        
            GlAccountGroup_9405,        
            GlAccountGroup_9406,        
            GlAccountGroup_9407,        
            GlAccountGroup_9408,        
            GlAccountGroup_9409,        
            GlAccountGroup_9410,        
            GlAccountGroup_9411,        
            GlAccountGroup_9412,        
            GlAccountGroup_9413,        
            GlAccountGroup_9414,        
            GlAccountGroup_9415,        
            GlAccountGroup_9416,        
            GlAccountGroup_9417,        
            GlAccountGroup_9418,        
            GlAccountGroup_9419,        
            GlAccountGroup_9420,        
            GlAccountGroup_9421,        
            GlAccountGroup_9422,        
            GlAccountGroup_9423,        
            GlAccountGroup_9424,        
            GlAccountGroup_9425,        
            GlAccountGroup_9426,        
            GlAccountGroup_9427,        
            GlAccountGroup_9428,        
            GlAccountGroup_9429,        
            GlAccountGroup_9430,        
            GlAccountGroup_9431,        
            GlAccountGroup_9432,        
            GlAccountGroup_9801,        
            GlAccountGroup_9802,        
            GlAccountGroup_9803,        
            GlAccountGroup_9804,        
            GlAccountGroup_9805,        
            GlAccountGroup_9806);

    public static final List<CustomMethodTypeData> customMethodTypeList=ImmutableList.of(        
            CustomMethodType_CC_AUTH,        
            CustomMethodType_CC_CAPTURE,        
            CustomMethodType_CC_REFUND,        
            CustomMethodType_CC_RELEASE,        
            CustomMethodType_CC_CREDIT,        
            CustomMethodType_EFT_AUTH,        
            CustomMethodType_EFT_RELEASE,        
            CustomMethodType_FIN_AUTH,        
            CustomMethodType_FIN_CAPTURE,        
            CustomMethodType_FIN_REFUND,        
            CustomMethodType_FIN_RELEASE,        
            CustomMethodType_FIN_PURCHASE,        
            CustomMethodType_GIFT_AUTH,        
            CustomMethodType_GIFT_CAPTURE,        
            CustomMethodType_GIFT_REFUND,        
            CustomMethodType_GIFT_RELEASE,        
            CustomMethodType_GIFT_PURCHASE,        
            CustomMethodType_PAYPAL_AUTH,        
            CustomMethodType_PAYPAL_CAPTURE,        
            CustomMethodType_PAYPAL_REFUND,        
            CustomMethodType_PAYPAL_RELEASE,        
            CustomMethodType_HOOK,        
            CustomMethodType_INVOICE_HOOK,        
            CustomMethodType_QUOTE_HOOK,        
            CustomMethodType_ORDER_HOOK,        
            CustomMethodType_DEPRECIATION_FORMULA);

    public static final List<CustomScreenTypeData> customScreenTypeList=ImmutableList.of(        
            CustomScreenType_CST_INVOICE_TPL,        
            CustomScreenType_CST_ORDER_TPL,        
            CustomScreenType_CST_QUOTE_TPL);

    public static final List<FixedAssetTypeData> fixedAssetTypeList=ImmutableList.of(        
            FixedAssetType_EQUIPMENT,        
            FixedAssetType_PRODUCTION_EQUIPMENT,        
            FixedAssetType_GROUP_EQUIPMENT,        
            FixedAssetType_OTHER_FIXED_ASSET,        
            FixedAssetType_PROPERTY,        
            FixedAssetType_VEHICLE,        
            FixedAssetType_REAL_ESTATE,        
            FixedAssetType_COMPUTER_SOFTWARE,        
            FixedAssetType_COMPUTER_HARDWARE);

    public static final List<PaymentGatewayConfigTypeData> paymentGatewayConfigTypeList=ImmutableList.of(        
            PaymentGatewayConfigType_PAY_GATWY_SAGEPAY,        
            PaymentGatewayConfigType_PAY_GATWY_AUTH_NET,        
            PaymentGatewayConfigType_PAY_GATWY_CYBERSRC,        
            PaymentGatewayConfigType_PAY_GATWY_EWAY,        
            PaymentGatewayConfigType_PAY_GATWY_PAYFLOWPRO,        
            PaymentGatewayConfigType_PAY_GATWY_PAYPAL,        
            PaymentGatewayConfigType_PAY_GATWY_CLRCOMRC,        
            PaymentGatewayConfigType_PAY_GATWY_WORLDPAY,        
            PaymentGatewayConfigType_PAY_GATWY_ORBITAL,        
            PaymentGatewayConfigType_PAY_GATWY_SECUREPAY);

    public static final List<SettlementTermData> settlementTermList=ImmutableList.of(        
            SettlementTerm_COD,        
            SettlementTerm_NET_15,        
            SettlementTerm_NET_30,        
            SettlementTerm_NET_60,        
            SettlementTerm_NET_90);

}
