package com.bluecc.hubs.stereotypes;

import com.google.common.collect.ImmutableList;
import java.util.List;
import static com.bluecc.hubs.stereotypes.PartySeedData.*;import com.bluecc.hubs.stub.PartyIdentificationTypeData;
import com.bluecc.hubs.stub.ContactMechTypeData;
import com.bluecc.hubs.stub.EnumerationData;
import com.bluecc.hubs.stub.PartyRelationshipTypeData;
import com.bluecc.hubs.stub.RoleTypeData;
import com.bluecc.hubs.stub.PartyContentTypeData;
import com.bluecc.hubs.stub.EnumerationTypeData;
import com.bluecc.hubs.stub.CommunicationEventPrpTypData;
import com.bluecc.hubs.stub.TermTypeData;
import com.bluecc.hubs.stub.StatusItemData;
import com.bluecc.hubs.stub.StatusValidChangeData;
import com.bluecc.hubs.stub.CommunicationEventTypeData;
import com.bluecc.hubs.stub.ContactMechTypePurposeData;
import com.bluecc.hubs.stub.PartyClassificationTypeData;
import com.bluecc.hubs.stub.StatusTypeData;
import com.bluecc.hubs.stub.SecurityGroupPermissionData;
import com.bluecc.hubs.stub.UserPreferenceData;
import com.bluecc.hubs.stub.PartyQualTypeData;
import com.bluecc.hubs.stub.PartyTypeData;
import com.bluecc.hubs.stub.SecurityPermissionData;
import com.bluecc.hubs.stub.ContactMechPurposeTypeData;

public final class PartySeedDataList {
    public static final List<PartyIdentificationTypeData> partyIdentificationTypeList=ImmutableList.of(        
            PartyIdentificationType_PARTY_IMPORT);

    public static final List<ContactMechTypeData> contactMechTypeList=ImmutableList.of(        
            ContactMechType_ELECTRONIC_ADDRESS,        
            ContactMechType_POSTAL_ADDRESS,        
            ContactMechType_TELECOM_NUMBER,        
            ContactMechType_EMAIL_ADDRESS,        
            ContactMechType_IP_ADDRESS,        
            ContactMechType_DOMAIN_NAME,        
            ContactMechType_WEB_ADDRESS,        
            ContactMechType_INTERNAL_PARTYID,        
            ContactMechType_FTP_ADDRESS);

    public static final List<EnumerationData> enumerationList=ImmutableList.of(        
            Enumeration_EMPS_FULLTIME,        
            Enumeration_EMPS_PARTTIME,        
            Enumeration_EMPS_SELF,        
            Enumeration_EMPS_HOUSE,        
            Enumeration_EMPS_RETIRED,        
            Enumeration_EMPS_STUDENT,        
            Enumeration_EMPS_UNEMP,        
            Enumeration_SINGLE,        
            Enumeration_MARRIED,        
            Enumeration_PRESS_OWN,        
            Enumeration_PRESS_PVT_TENANT,        
            Enumeration_PRESS_PUB_TENANT,        
            Enumeration_PRESS_PARENTS,        
            Enumeration_PARTY_REGIS_CONFIRM,        
            Enumeration_UPD_PRSNL_INF_CNFRM,        
            Enumeration_PRDS_EMAIL_VERIFY,        
            Enumeration_PRDS_PARTYINV_EMAIL,        
            Enumeration_CONT_NOTI_EMAIL,        
            Enumeration_PRDS_CUST_ACTIVATED,        
            Enumeration_UNSUB_CONT_LIST_NOTI,        
            Enumeration_SUB_CONT_LIST_NOTI,        
            Enumeration_UNSUB_CONT_LIST_VERI,        
            Enumeration_CONT_EMAIL_TEMPLATE,        
            Enumeration_ORGANIZATION_PARTY,        
            Enumeration_VISUAL_THEME);

    public static final List<PartyRelationshipTypeData> partyRelationshipTypeList=ImmutableList.of(        
            PartyRelationshipType_AGENT,        
            PartyRelationshipType_CHILD,        
            PartyRelationshipType_CONTACT_REL,        
            PartyRelationshipType_LEAD_REL,        
            PartyRelationshipType_LEAD_OWNER,        
            PartyRelationshipType_CUSTOMER_REL,        
            PartyRelationshipType_DISTRIBUTION_CHANNEL,        
            PartyRelationshipType_EMPLOYMENT,        
            PartyRelationshipType_FRIEND,        
            PartyRelationshipType_GROUP_ROLLUP,        
            PartyRelationshipType_HOST_SERVER_VISITOR,        
            PartyRelationshipType_VISITOR_ISP,        
            PartyRelationshipType_MANAGER,        
            PartyRelationshipType_PARENT,        
            PartyRelationshipType_PARTNERSHIP,        
            PartyRelationshipType_SALES_AFFILIATE,        
            PartyRelationshipType_SPOUSE,        
            PartyRelationshipType_SUPPLIER_REL,        
            PartyRelationshipType_WEB_MASTER_ASSIGNMEN,        
            PartyRelationshipType_ACCOUNT,        
            PartyRelationshipType_ASSISTANT,        
            PartyRelationshipType_OWNER,        
            PartyRelationshipType_PARENT_ACCOUNT,        
            PartyRelationshipType_REPORTS_TO,        
            PartyRelationshipType_LEAD_OWN_GRP_MEMBER);

    public static final List<RoleTypeData> roleTypeList=ImmutableList.of(        
            RoleType_MAIN_ROLE,        
            RoleType_ACCOUNT_LEAD,        
            RoleType_ADMIN,        
            RoleType_AGENT,        
            RoleType_AUTOMATED_AGENT_ROLE,        
            RoleType_CALENDAR_ROLE,        
            RoleType_CLIENT,        
            RoleType_COMMEVENT_ROLE,        
            RoleType_CONSUMER,        
            RoleType_CONTRACTOR,        
            RoleType_CUSTOMER,        
            RoleType_DISTRIBUTION_CHANNEL,        
            RoleType_ISP,        
            RoleType_HOSTING_SERVER,        
            RoleType_MANUFACTURER,        
            RoleType__NA_,        
            RoleType_ORGANIZATION_ROLE,        
            RoleType_OWNER,        
            RoleType_PROSPECT,        
            RoleType_PERSON_ROLE,        
            RoleType_REFERRER,        
            RoleType_REQUEST_ROLE,        
            RoleType_REQ_MANAGER,        
            RoleType_REQ_REQUESTER,        
            RoleType_REQ_TAKER,        
            RoleType_REQ_RESPOND,        
            RoleType_SFA_ROLE,        
            RoleType_SHAREHOLDER,        
            RoleType_SUBSCRIBER,        
            RoleType_VENDOR,        
            RoleType_VISITOR,        
            RoleType_WEB_MASTER,        
            RoleType_WORKFLOW_ROLE,        
            RoleType_ACCOUNTANT,        
            RoleType_ACCOUNT,        
            RoleType_ADDRESSEE,        
            RoleType_ASSOCIATION,        
            RoleType_BILL_FROM_VENDOR,        
            RoleType_BILL_TO_CUSTOMER,        
            RoleType_BCC,        
            RoleType_BULK_CUSTOMER,        
            RoleType_CAL_ATTENDEE,        
            RoleType_CAL_DELEGATE,        
            RoleType_CAL_HOST,        
            RoleType_CAL_ORGANIZER,        
            RoleType_CAL_OWNER,        
            RoleType_CARRIER,        
            RoleType_COMPETITOR,        
            RoleType_CONTACT,        
            RoleType_CC,        
            RoleType_ORIGINATOR,        
            RoleType_DISTRIBUTOR,        
            RoleType_EMPLOYEE,        
            RoleType_END_USER_CUSTOMER,        
            RoleType_HOUSEHOLD,        
            RoleType_INTERNAL_ORGANIZATIO,        
            RoleType_LEAD,        
            RoleType_LTD_ADMIN,        
            RoleType_ORGANIZATION_UNIT,        
            RoleType_PARTNER,        
            RoleType_PLACING_CUSTOMER,        
            RoleType_REGULATORY_AGENCY,        
            RoleType_SALES_REP,        
            RoleType_SHIP_FROM_VENDOR,        
            RoleType_SHIP_TO_CUSTOMER,        
            RoleType_SPONSOR,        
            RoleType_SPOUSE,        
            RoleType_SUPPLIER_AGENT,        
            RoleType_SUPPLIER,        
            RoleType_TAX_AUTHORITY,        
            RoleType_UNION,        
            RoleType_WF_OWNER,        
            RoleType_GOV_AGENCY,        
            RoleType_AFFILIATE,        
            RoleType_BUYER,        
            RoleType_CASHIER,        
            RoleType_DEPARTMENT,        
            RoleType_DIVISION,        
            RoleType_FAMILY_MEMBER,        
            RoleType_MANAGER,        
            RoleType_ORDER_CLERK,        
            RoleType_OTHER_INTERNAL_ORGAN,        
            RoleType_OTHER_ORGANIZATION_U,        
            RoleType_PARENT_ORGANIZATION,        
            RoleType_PACKER,        
            RoleType_PICKER,        
            RoleType_RECEIVER,        
            RoleType_SHIPMENT_CLERK,        
            RoleType_STOCKER,        
            RoleType_SUBSIDIARY,        
            RoleType_WORKER,        
            RoleType_EMAIL_ADMIN);

    public static final List<PartyContentTypeData> partyContentTypeList=ImmutableList.of(        
            PartyContentType_INTERNAL,        
            PartyContentType_USERDEF,        
            PartyContentType_LGOIMGURL,        
            PartyContentType_VNDSHPINF);

    public static final List<EnumerationTypeData> enumerationTypeList=ImmutableList.of(        
            EnumerationType_EMPLOY_STTS,        
            EnumerationType_MARITAL_STATUS,        
            EnumerationType_PTY_RESID_STTS,        
            EnumerationType_PARTY_EMAIL,        
            EnumerationType_USER_PREF_GROUPS,        
            EnumerationType_GLOBAL_PREFERENCES);

    public static final List<CommunicationEventPrpTypData> communicationEventPrpTypList=ImmutableList.of(        
            CommunicationEventPrpTyp_ACTIVITY_REQUEST,        
            CommunicationEventPrpTyp_CONFERENCE,        
            CommunicationEventPrpTyp_CUSTOMER_SERVICE_CAL,        
            CommunicationEventPrpTyp_INQUIRY,        
            CommunicationEventPrpTyp_MEETING,        
            CommunicationEventPrpTyp_SALES_FOLLOW_UP,        
            CommunicationEventPrpTyp_SEMINAR,        
            CommunicationEventPrpTyp_SUPPORT_CALL);

    public static final List<TermTypeData> termTypeList=ImmutableList.of(        
            TermType_FINANCIAL_TERM,        
            TermType_FIN_PAYMENT_TERM,        
            TermType_FIN_PAY_NETDAYS_1,        
            TermType_FIN_PAY_NETDAYS_2,        
            TermType_FIN_PAY_NETDAYS_3,        
            TermType_FIN_PAYMENT_DISC,        
            TermType_FIN_PAYMENT_FIXDAY,        
            TermType_FIN_LATE_FEE_TERM,        
            TermType_FIN_COLLECT_TERM,        
            TermType_FIN_NORTN_ITEM_TERM,        
            TermType_INCENTIVE,        
            TermType_LEGAL_TERM,        
            TermType_THRESHOLD,        
            TermType_CLAUSE_FOR_RENEWAL,        
            TermType_AGREEMENT_TERMINATIO,        
            TermType_INDEMNIFICATION,        
            TermType_NON_COMPETE,        
            TermType_EXCLUSIVE_RELATIONSH,        
            TermType_COMMISSION_TERM,        
            TermType_FIN_COMM_FIXED,        
            TermType_FIN_COMM_VARIABLE,        
            TermType_FIN_COMM_MIN,        
            TermType_FIN_COMM_MAX,        
            TermType_INCO_TERM,        
            TermType_INCO_TERM_2020,        
            TermType_INCO_TERM_2020_EXW,        
            TermType_INCO_TERM_2020_FCA,        
            TermType_INCO_TERM_2020_FAS,        
            TermType_INCO_TERM_2020_FOB,        
            TermType_INCO_TERM_2020_CPT,        
            TermType_INCO_TERM_2020_CFR,        
            TermType_INCO_TERM_2020_CIF,        
            TermType_INCO_TERM_2020_CIP,        
            TermType_INCO_TERM_2020_DPU,        
            TermType_INCO_TERM_2020_DAP,        
            TermType_INCO_TERM_2020_DDP,        
            TermType_INCO_TERM_2010,        
            TermType_EXW,        
            TermType_FCA,        
            TermType_FAS,        
            TermType_FOB,        
            TermType_CFR,        
            TermType_CIF,        
            TermType_CPT,        
            TermType_CIP,        
            TermType_DDP,        
            TermType_INCO_TERM_2000,        
            TermType_DAF,        
            TermType_DES,        
            TermType_DEQ,        
            TermType_DDU,        
            TermType_PURCHASING,        
            TermType_PURCH_VENDOR_ID,        
            TermType_PURCH_FREIGHT,        
            TermType_OTHER_TERM);

    public static final List<StatusItemData> statusItemList=ImmutableList.of(        
            StatusItem_PARTY_ENABLED,        
            StatusItem_PARTY_DISABLED,        
            StatusItem_COM_PENDING,        
            StatusItem_COM_ENTERED,        
            StatusItem_COM_IN_PROGRESS,        
            StatusItem_COM_UNKNOWN_PARTY,        
            StatusItem_COM_COMPLETE,        
            StatusItem_COM_RESOLVED,        
            StatusItem_COM_REFERRED,        
            StatusItem_COM_BOUNCED,        
            StatusItem_COM_CANCELLED,        
            StatusItem_COM_ROLE_CREATED,        
            StatusItem_COM_ROLE_READ,        
            StatusItem_COM_ROLE_COMPLETED,        
            StatusItem_PARTYREL_CREATED,        
            StatusItem_PARTYREL_EXPIRED,        
            StatusItem_PARTYINV_SENT,        
            StatusItem_PARTYINV_PENDING,        
            StatusItem_PARTYINV_ACCEPTED,        
            StatusItem_PARTYINV_DECLINED,        
            StatusItem_PARTYINV_CANCELLED);

    public static final List<StatusValidChangeData> statusValidChangeList=ImmutableList.of(        
            StatusValidChange_PARTY_ENABLED_PARTY_DISABLED,        
            StatusValidChange_PARTY_DISABLED_PARTY_ENABLED,        
            StatusValidChange_COM_ENTERED_COM_PENDING,        
            StatusValidChange_COM_ENTERED_COM_IN_PROGRESS,        
            StatusValidChange_COM_ENTERED_COM_COMPLETE,        
            StatusValidChange_COM_PENDING_COM_ENTERED,        
            StatusValidChange_COM_PENDING_COM_IN_PROGRESS,        
            StatusValidChange_COM_IN_PROGRESS_COM_COMPLETE,        
            StatusValidChange_COM_IN_PROGRESS_COM_BOUNCED,        
            StatusValidChange_COM_COMPLETE_COM_RESOLVED,        
            StatusValidChange_COM_COMPLETE_COM_REFERRED,        
            StatusValidChange_COM_COMPLETE_COM_BOUNCED,        
            StatusValidChange_COM_UNKNOWN_PARTY_COM_COMPLETE,        
            StatusValidChange_COM_UNKNOWN_PARTY_COM_ENTERED,        
            StatusValidChange_COM_PENDING_COM_COMPLETE,        
            StatusValidChange_COM_ENTERED_COM_CANCELLED,        
            StatusValidChange_COM_PENDING_COM_CANCELLED,        
            StatusValidChange_COM_IN_PROGRESS_COM_CANCELLED,        
            StatusValidChange_COM_COMPLETE_COM_CANCELLED,        
            StatusValidChange_COM_RESOLVED_COM_CANCELLED,        
            StatusValidChange_COM_REFERRED_COM_CANCELLED,        
            StatusValidChange_COM_UNKNOWN_PARTY_COM_CANCELLED,        
            StatusValidChange_COM_ROLE_CREATED_COM_ROLE_READ,        
            StatusValidChange_COM_ROLE_CREATED_COM_ROLE_COMPLETED,        
            StatusValidChange_COM_ROLE_READ_COM_ROLE_COMPLETED,        
            StatusValidChange_PARTYREL_CREATED_PARTYREL_EXPIRED,        
            StatusValidChange_PARTYINV_SENT_PARTYINV_PENDING,        
            StatusValidChange_PARTYINV_SENT_PARTYINV_ACCEPTED,        
            StatusValidChange_PARTYINV_SENT_PARTYINV_DECLINED,        
            StatusValidChange_PARTYINV_SENT_PARTYINV_CANCELLED,        
            StatusValidChange_PARTYINV_PENDING_PARTYINV_ACCEPTED,        
            StatusValidChange_PARTYINV_PENDING_PARTYINV_CANCELLED);

    public static final List<CommunicationEventTypeData> communicationEventTypeList=ImmutableList.of(        
            CommunicationEventType_EMAIL_COMMUNICATION,        
            CommunicationEventType_FACE_TO_FACE_COMMUNI,        
            CommunicationEventType_FAX_COMMUNICATION,        
            CommunicationEventType_LETTER_CORRESPONDENC,        
            CommunicationEventType_PHONE_COMMUNICATION,        
            CommunicationEventType_WEB_SITE_COMMUNICATI,        
            CommunicationEventType_COMMENT_NOTE,        
            CommunicationEventType_AUTO_EMAIL_COMM,        
            CommunicationEventType_FILE_TRANSFER_COMM);

    public static final List<ContactMechTypePurposeData> contactMechTypePurposeList=ImmutableList.of(        
            ContactMechTypePurpose_EMAIL_ADDRESS_BILLING_EMAIL,        
            ContactMechTypePurpose_EMAIL_ADDRESS_MARKETING_EMAIL,        
            ContactMechTypePurpose_EMAIL_ADDRESS_PAYMENT_EMAIL,        
            ContactMechTypePurpose_EMAIL_ADDRESS_ORDER_EMAIL,        
            ContactMechTypePurpose_EMAIL_ADDRESS_OTHER_EMAIL,        
            ContactMechTypePurpose_EMAIL_ADDRESS_PRIMARY_EMAIL,        
            ContactMechTypePurpose_POSTAL_ADDRESS_SHIPPING_LOCATION,        
            ContactMechTypePurpose_POSTAL_ADDRESS_SHIP_ORIG_LOCATION,        
            ContactMechTypePurpose_POSTAL_ADDRESS_BILLING_LOCATION,        
            ContactMechTypePurpose_POSTAL_ADDRESS_PAYMENT_LOCATION,        
            ContactMechTypePurpose_POSTAL_ADDRESS_GENERAL_LOCATION,        
            ContactMechTypePurpose_POSTAL_ADDRESS_PUR_RET_LOCATION,        
            ContactMechTypePurpose_POSTAL_ADDRESS_PRIMARY_LOCATION,        
            ContactMechTypePurpose_POSTAL_ADDRESS_PREVIOUS_LOCATION,        
            ContactMechTypePurpose_TELECOM_NUMBER_FAX_NUMBER,        
            ContactMechTypePurpose_TELECOM_NUMBER_FAX_NUMBER_SEC,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_DID,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_HOME,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_MOBILE,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_WORK,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_WORK_SEC,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_SHIPPING,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_SHIP_ORIG,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_BILLING,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_PAYMENT,        
            ContactMechTypePurpose_TELECOM_NUMBER_PRIMARY_PHONE,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_QUICK,        
            ContactMechTypePurpose_TELECOM_NUMBER_FAX_SHIPPING,        
            ContactMechTypePurpose_TELECOM_NUMBER_FAX_BILLING,        
            ContactMechTypePurpose_TELECOM_NUMBER_PHONE_ASSISTANT,        
            ContactMechTypePurpose_WEB_ADDRESS_PRIMARY_WEB_URL,        
            ContactMechTypePurpose_WEB_ADDRESS_TWITTER_URL,        
            ContactMechTypePurpose_WEB_ADDRESS_FACEBOOK_URL,        
            ContactMechTypePurpose_WEB_ADDRESS_LINKEDIN_URL);

    public static final List<PartyClassificationTypeData> partyClassificationTypeList=ImmutableList.of(        
            PartyClassificationType_EEOC_CLASSIFICATION,        
            PartyClassificationType_MINORITY_CLASSIFICAT,        
            PartyClassificationType_INCOME_CLASSIFICATIO,        
            PartyClassificationType_INDUSTRY_CLASSIFICAT,        
            PartyClassificationType_ORGANIZATION_CLASSIF,        
            PartyClassificationType_PERSON_CLASSIFICATIO,        
            PartyClassificationType_SIZE_CLASSIFICATION,        
            PartyClassificationType_TRADE_CLASSIFICATION,        
            PartyClassificationType_TRADE_WHOLE_CLASSIFI,        
            PartyClassificationType_TRADE_RETAIL_CLASSIF,        
            PartyClassificationType_ANNUAL_REVENUE,        
            PartyClassificationType_NUMBER_OF_EMPLOYEES,        
            PartyClassificationType_VALUE_RATING,        
            PartyClassificationType_SIC_CODE,        
            PartyClassificationType_OWNERSHIP);

    public static final List<StatusTypeData> statusTypeList=ImmutableList.of(        
            StatusType_PARTY_STATUS,        
            StatusType_CASE_STATUS,        
            StatusType_COM_EVENT_STATUS,        
            StatusType_COM_EVENT_ROL_STATUS,        
            StatusType_PARTY_REL_STATUS,        
            StatusType_PARTY_INV_STATUS);

    public static final List<SecurityGroupPermissionData> securityGroupPermissionList=ImmutableList.of(        
            SecurityGroupPermission_SUPER_PARTYMGR_ADMIN_,        
            SecurityGroupPermission_SUPER_SECURITY_ADMIN_);

    public static final List<UserPreferenceData> userPreferenceList=ImmutableList.of(        
            UserPreference__NA__ORGANIZATION_PARTY);

    public static final List<PartyQualTypeData> partyQualTypeList=ImmutableList.of(        
            PartyQualType_EXPERIENCE,        
            PartyQualType_CERTIFICATION,        
            PartyQualType_DEGREE);

    public static final List<PartyTypeData> partyTypeList=ImmutableList.of(        
            PartyType_AUTOMATED_AGENT,        
            PartyType_PERSON,        
            PartyType_PARTY_GROUP,        
            PartyType_INFORMAL_GROUP,        
            PartyType_FAMILY,        
            PartyType_TEAM,        
            PartyType_LEGAL_ORGANIZATION,        
            PartyType_CORPORATION,        
            PartyType_GOVERNMENT_AGENCY);

    public static final List<SecurityPermissionData> securityPermissionList=ImmutableList.of(        
            SecurityPermission_PARTYMGR_VIEW,        
            SecurityPermission_PARTYMGR_CREATE,        
            SecurityPermission_PARTYMGR_UPDATE,        
            SecurityPermission_PARTYMGR_DELETE,        
            SecurityPermission_PARTYMGR_ADMIN,        
            SecurityPermission_PARTYMGR_NOTE,        
            SecurityPermission_PARTYMGR_STS_UPDATE,        
            SecurityPermission_PARTYMGR_GRP_UPDATE,        
            SecurityPermission_PARTYMGR_REL_CREATE,        
            SecurityPermission_PARTYMGR_REL_UPDATE,        
            SecurityPermission_PARTYMGR_REL_DELETE,        
            SecurityPermission_PARTYMGR_ROLE_CREATE,        
            SecurityPermission_PARTYMGR_ROLE_DELETE,        
            SecurityPermission_PARTYMGR_PCM_CREATE,        
            SecurityPermission_PARTYMGR_PCM_UPDATE,        
            SecurityPermission_PARTYMGR_PCM_DELETE,        
            SecurityPermission_PARTYMGR_SRC_CREATE,        
            SecurityPermission_PARTYMGR_QAL_CREATE,        
            SecurityPermission_PARTYMGR_QAL_UPDATE,        
            SecurityPermission_PARTYMGR_QAL_DELETE,        
            SecurityPermission_PARTYMGR_CME_CREATE,        
            SecurityPermission_PARTYMGR_CME_UPDATE,        
            SecurityPermission_PARTYMGR_CME_DELETE,        
            SecurityPermission_PARTYMGR_CME_EMAIL_CREATE,        
            SecurityPermission_PARTYMGR_CME_EMAIL_UPDATE,        
            SecurityPermission_PARTYMGR_CME_EMAIL_DELETE,        
            SecurityPermission_PARTYMGR_CME_NOTE_CREATE,        
            SecurityPermission_SECURITY_VIEW,        
            SecurityPermission_SECURITY_CREATE,        
            SecurityPermission_SECURITY_UPDATE,        
            SecurityPermission_SECURITY_DELETE,        
            SecurityPermission_SECURITY_ADMIN);

    public static final List<ContactMechPurposeTypeData> contactMechPurposeTypeList=ImmutableList.of(        
            ContactMechPurposeType_SHIPPING_LOCATION,        
            ContactMechPurposeType_SHIP_ORIG_LOCATION,        
            ContactMechPurposeType_BILLING_LOCATION,        
            ContactMechPurposeType_PAYMENT_LOCATION,        
            ContactMechPurposeType_GENERAL_LOCATION,        
            ContactMechPurposeType_PUR_RET_LOCATION,        
            ContactMechPurposeType_PRIMARY_LOCATION,        
            ContactMechPurposeType_PREVIOUS_LOCATION,        
            ContactMechPurposeType_PHONE_SHIPPING,        
            ContactMechPurposeType_PHONE_SHIP_ORIG,        
            ContactMechPurposeType_PHONE_BILLING,        
            ContactMechPurposeType_PHONE_DID,        
            ContactMechPurposeType_PHONE_PAYMENT,        
            ContactMechPurposeType_PHONE_HOME,        
            ContactMechPurposeType_PHONE_WORK,        
            ContactMechPurposeType_PHONE_WORK_SEC,        
            ContactMechPurposeType_FAX_NUMBER,        
            ContactMechPurposeType_FAX_NUMBER_SEC,        
            ContactMechPurposeType_FAX_SHIPPING,        
            ContactMechPurposeType_FAX_BILLING,        
            ContactMechPurposeType_PHONE_MOBILE,        
            ContactMechPurposeType_PHONE_ASSISTANT,        
            ContactMechPurposeType_PRIMARY_PHONE,        
            ContactMechPurposeType_PHONE_QUICK,        
            ContactMechPurposeType_MARKETING_EMAIL,        
            ContactMechPurposeType_PRIMARY_EMAIL,        
            ContactMechPurposeType_BILLING_EMAIL,        
            ContactMechPurposeType_PAYMENT_EMAIL,        
            ContactMechPurposeType_OTHER_EMAIL,        
            ContactMechPurposeType_SUPPORT_EMAIL,        
            ContactMechPurposeType_ORDER_EMAIL,        
            ContactMechPurposeType_PRIMARY_WEB_URL,        
            ContactMechPurposeType_TWITTER_URL,        
            ContactMechPurposeType_FACEBOOK_URL,        
            ContactMechPurposeType_LINKEDIN_URL);

}
