package com.bluecc.gentool.descriptor;

import lombok.Getter;

public enum EntityNames implements INameSymbol{

    ShipmentRouteSegment("ShipmentRouteSegment", "Shipment Route Segment"),
    Invoice("Invoice", "Invoice"),
    OrderAdjustment("OrderAdjustment", "Order Adjustment"),
    Product("Product", "Product"),
    CarrierShipmentBoxType("CarrierShipmentBoxType", "Carrier Shipment Method"),
    FixedAsset("FixedAsset", "Fixed Asset"),
    WebAnalyticsConfig("WebAnalyticsConfig", "Web Analytics Configuration"),
    ProductCategoryRollup("ProductCategoryRollup", "Product Category Rollup"),
    PaymentGatewayResponse("PaymentGatewayResponse", "Payment Gateway Response"),
    ShipmentItemBilling("ShipmentItemBilling", "Shipment Item Billing"),
    ProductPromoAction("ProductPromoAction", "Product Promotion Action"),
    ShipmentCostEstimate("ShipmentCostEstimate", "Shipment Cost Estimate"),
    SecurityGroupPermission("SecurityGroupPermission", "Security Component - Security Group Permission"),
    ProductStoreKeywordOvrd("ProductStoreKeywordOvrd", "Product Store Inventory Facility Applicability"),
    ProductAssoc("ProductAssoc", "Product Association"),
    FixedAssetProduct("FixedAssetProduct", "Fixed Asset Product Representation"),
    PaymentApplication("PaymentApplication", "Payment Application"),
    CustRequest("CustRequest", "CustRequest"),
    ShipmentReceipt("ShipmentReceipt", "Shipment Receipt"),
    InventoryItemDetail("InventoryItemDetail", "Inventory Item Detail"),
    OrderAdjustmentBilling("OrderAdjustmentBilling", "Order Adjustment Billing"),
    ProductFeaturePrice("ProductFeaturePrice", "Product Feature Price"),
    ProductConfigOption("ProductConfigOption", "Product Configuration Options"),
    PostalAddress("PostalAddress", "Postal Address"),
    ProductFacilityAssoc("ProductFacilityAssoc", "Define associations between Product facilities"),
    OrderItemPriceInfo("OrderItemPriceInfo", "Order Item Price Info"),
    WorkEffortGoodStandard("WorkEffortGoodStandard", "Work Effort Good Standard"),
    Person("Person", "Person"),
    ProductStoreRole("ProductStoreRole", "Product Store Role Association"),
    PartyContactMech("PartyContactMech", "Party Contact Mechanism"),
    ProductStoreEmailSetting("ProductStoreEmailSetting", "Product Store Email Settings"),
    ElectronicText("ElectronicText", "Electronic Text"),
    ItemIssuance("ItemIssuance", "Item Issuance"),
    PartyGroup("PartyGroup", "Party Group"),
    ProductPromoProduct("ProductPromoProduct", "Product Promotion Category"),
    ProductReview("ProductReview", "Product Review"),
    OrderPaymentPreference("OrderPaymentPreference", "The Order Payment Preference"),
    SupplierProduct("SupplierProduct", "Supplier Product"),
    OrderStatus("OrderStatus", "Order Status"),
    Party("Party", "Party"),
    AgreementItem("AgreementItem", "Agreement Item"),
    PartyTaxAuthInfo("PartyTaxAuthInfo", "Party Tax Information"),
    AcctgTrans("AcctgTrans", "Accounting Transaction"),
    DataResource("DataResource", "Data Object"),
    ShipmentItem("ShipmentItem", "Shipment Item"),
    FacilityContactMech("FacilityContactMech", "Facility Contact Mechanism"),
    Agreement("Agreement", "Agreement"),
    ProdCatalogCategory("ProdCatalogCategory", "Catalog Category Association"),
    ProductCategoryRole("ProductCategoryRole", "Product Category Role"),
    OrderItem("OrderItem", "Order Item"),
    ShipmentTimeEstimate("ShipmentTimeEstimate", "Shipment Time Estimation Entity"),
    ProductCategoryContent("ProductCategoryContent", "Product Category Data Object"),
    OrderItemShipGroupAssoc("OrderItemShipGroupAssoc", "Order Item Package Association"),
    ContentAssoc("ContentAssoc", "Content Association"),
    QuoteItem("QuoteItem", "Quote Item"),
    ProdCatalog("ProdCatalog", "Catalog"),
    ProductPromoCond("ProductPromoCond", "Product Promotion Condition"),
    FacilityLocation("FacilityLocation", "Facility Location"),
    ProductPromoCategory("ProductPromoCategory", "Product Promotion Category"),
    PartyStatus("PartyStatus", "Tracks a history of the status of a Party"),
    ProductFacilityLocation("ProductFacilityLocation", "Product Facility"),
    ShipmentBoxType("ShipmentBoxType", "Shipment Contact Mechanism Type"),
    ShipmentPackageRouteSeg("ShipmentPackageRouteSeg", "Shipment Package Route Segment"),
    GeoPoint("GeoPoint", "Geographic Location"),
    SubscriptionResource("SubscriptionResource", "Subscription Resource"),
    ProductFeatureAppl("ProductFeatureAppl", "Product Feature Applicability"),
    PartyContactMechPurpose("PartyContactMechPurpose", "Party Contact Mechanism Purpose"),
    RecurrenceInfo("RecurrenceInfo", "Recurrence Info"),
    ProductFeatureCategory("ProductFeatureCategory", "Product Feature Category"),
    FacilityLocationGeoPoint("FacilityLocationGeoPoint", "Facility Location Geo Location with history"),
    UserLoginSecurityGroup("UserLoginSecurityGroup", "Security Component - User Login Security Group"),
    ProductStoreCatalog("ProductStoreCatalog", "Product Store Catalog Association"),
    UserLogin("UserLogin", "UserLogin"),
    ProductPriceRule("ProductPriceRule", "Product Pice Rule"),
    PartyRole("PartyRole", "Party Role"),
    ProductFacility("ProductFacility", "Product Facility"),
    PartyGeoPoint("PartyGeoPoint", "Party Geo Location with history"),
    OrderHeader("OrderHeader", "Order Header"),
    CarrierShipmentMethod("CarrierShipmentMethod", "Carrier Shipment Method"),
    Shipment("Shipment", "Shipment"),
    ShipmentPackageContent("ShipmentPackageContent", "Shipment Package Content"),
    SecurityGroup("SecurityGroup", "Security Component - Security Group"),
    ProductContent("ProductContent", "Product Data Object"),
    PartyRelationship("PartyRelationship", "Party Relationship"),
    ProductStoreShipmentMeth("ProductStoreShipmentMeth", "Product Store Carrier Shipment Method"),
    Payment("Payment", "Payment"),
    Content("Content", "Content"),
    ShipmentPackage("ShipmentPackage", "Shipment Package"),
    ProductStoreFacility("ProductStoreFacility", "Product Store Inventory Facility Applicability"),
    WebSite("WebSite", "WebSite"),
    ProductCategory("ProductCategory", "Product Category"),
    ProductStorePaymentSetting("ProductStorePaymentSetting", "Product Store Payment Settings"),
    PaymentMethod("PaymentMethod", "Payment Method"),
    ProductPriceCond("ProductPriceCond", "Product Price Condition"),
    InventoryItem("InventoryItem", "Inventory Item"),
    BillingAccountRole("BillingAccountRole", "Billing Account Role"),
    InvoiceItem("InvoiceItem", "Invoice Item"),
    ProductFeatureCategoryAppl("ProductFeatureCategoryAppl", "Product Feature Category Application"),
    ProductConfigItem("ProductConfigItem", "Product Configuration Question"),
    TelecomNumber("TelecomNumber", "Telecommunications Number"),
    ProductFeature("ProductFeature", "Product Feature"),
    ProductConfig("ProductConfig", "Product Configuration Templates"),
    ProductPromoCode("ProductPromoCode", "Product Promotion"),
    ProductStore("ProductStore", "Product Store"),
    ProductPrice("ProductPrice", "Product Price"),
    QuantityBreak("QuantityBreak", "Quantity Break"),
    ContactMech("ContactMech", "Contact Mechanism"),
    OrderItemShipGrpInvRes("OrderItemShipGrpInvRes", "Order Item Inventory Reservation"),
    ProductPromoRule("ProductPromoRule", "Product Promotion Rule"),
    OrderContactMech("OrderContactMech", "Order Contact Mechanism"),
    WorkEffort("WorkEffort", "WorkEffort"),
    ShipmentStatus("ShipmentStatus", "Shipment Status"),
    BillingAccount("BillingAccount", "Billing Account"),
    FacilityContactMechPurpose("FacilityContactMechPurpose", "Facility Contact Mechanism Purpose"),
    ProductKeyword("ProductKeyword", "Product Keyword"),
    CustRequestItem("CustRequestItem", "Customer Request Item"),
    OrderRole("OrderRole", "Order Role"),
    FixedAssetGeoPoint("FixedAssetGeoPoint", "Fixed Asset Geo Location with history"),
    RecurrenceRule("RecurrenceRule", "Recurrence Rule"),
    ProductStorePromoAppl("ProductStorePromoAppl", "Product Store Promotion Applicability"),
    ProductConfigProduct("ProductConfigProduct", "Product Configuration Option to Products"),
    ProductPriceAction("ProductPriceAction", "Product Price Action"),
    ShipmentMethodType("ShipmentMethodType", "Shipment Method Type"),
    QuoteTerm("QuoteTerm", "Quote Term"),
    AcctgTransEntry("AcctgTransEntry", "Transaction Entry"),
    OrderItemBilling("OrderItemBilling", "Order Item Billing"),
    OrderItemShipGroup("OrderItemShipGroup", "Order Item Ship Group"),
    CustRequestType("CustRequestType", "Customer Request Type"),
    AgreementProductAppl("AgreementProductAppl", "Agreement Product Application"),
    ProductSubscriptionResource("ProductSubscriptionResource", "Product Subscription Resource"),
    CreditCard("CreditCard", "Credit Card Information"),
    Quote("Quote", "Quote"),
    ProductPromo("ProductPromo", "Product Promotion"),
    ProductCategoryMember("ProductCategoryMember", "Product Category Member"),
    AgreementTerm("AgreementTerm", "Agreement Term"),
    ProductCategoryLink("ProductCategoryLink", "Product Category Link"),
    ProductFeatureIactn("ProductFeatureIactn", "Product Feature Interaction"),
    WorkEffortAssoc("WorkEffortAssoc", "Work Effort Association"),
    QuoteRole("QuoteRole", "Quote Role"),
    
    ;

    @Getter(onMethod_ = {@Override})
    public final String entityName;
    @Getter(onMethod_ = {@Override})
    public final String description;

    private EntityNames(String entityName, String description){
        this.entityName=entityName;
        this.description=description;
    }

}


