name: ProductCategory
relationMarks:
- bindFields: [productCategoryId]
  entityName: ProdCatalogCategory
  name: ProdCatalogCategory
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: Product
  name: PrimaryProduct
  relationType: many
  tags: [skip]
- bindFields: [primaryParentCategoryId]
  entityName: ProductCategory
  name: PrimaryParentProductCategory
  relationType: one
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductCategory
  name: PrimaryChildProductCategory
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductCategoryContent
  name: ProductCategoryContent
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductCategoryLink
  name: ProductCategoryLink
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductCategoryMember
  name: ProductCategoryMember
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductCategoryRole
  name: ProductCategoryRole
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductCategoryRollup
  name: CurrentProductCategoryRollup
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductCategoryRollup
  name: ParentProductCategoryRollup
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductFeatureCategoryAppl
  name: ProductFeatureCategoryAppl
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductPromoCategory
  name: ProductPromoCategory
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: ProductStoreSurveyAppl
  name: ProductStoreSurveyAppl
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: TaxAuthorityCategory
  name: TaxAuthorityCategory
  relationType: many
  tags: [skip]
- bindFields: [productCategoryId]
  entityName: TaxAuthorityRateProduct
  name: TaxAuthorityRateProduct
  relationType: many
  tags: [skip]
- bindFields: [tenantId]
  entityName: Tenant
  name: Tenant
  relationType: one
  tags: [skip]
