name: Product
relationMarks:
- bindFields: [productId]
  entityName: Agreement
  name: Agreement
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: AgreementProductAppl
  name: AgreementProductAppl
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: CustRequestItem
  name: CustRequestItem
  relationType: many
  tags: [skip]
- bindFields: [facilityId]
  entityName: Facility
  name: Facility
  relationType: one
  tags: [skip]
- bindFields: [productId]
  entityName: FixedAsset
  name: InstanceOfFixedAsset
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: FixedAssetProduct
  name: FixedAssetProduct
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: InventoryItem
  name: InventoryItem
  relationType: many
  tags: [normal]
- bindFields: [productId]
  entityName: InvoiceItem
  name: InvoiceItem
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: OrderItem
  name: OrderItem
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ProductAssoc
  name: MainProductAssoc
  relationType: many
  tags: [normal]
- bindFields: [productId]
  entityName: ProductAssoc
  name: AssocProductAssoc
  relationType: many
  tags: [skip]
- bindFields: [primaryProductCategoryId]
  entityName: ProductCategory
  name: PrimaryProductCategory
  relationType: one
  tags: [normal]
- bindFields: [productId]
  entityName: ProductCategoryMember
  name: ProductCategoryMember
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ProductConfig
  name: ProductProductConfig
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ProductConfigProduct
  name: ProductProductConfigProduct
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ProductContent
  name: ProductContent
  relationType: many
  tags: [normal]
- bindFields: [productId]
  entityName: ProductFacility
  name: ProductFacility
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ProductFacilityAssoc
  name: ProductFacilityAssoc
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ProductFacilityLocation
  name: ProductFacilityLocation
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ProductFeatureAppl
  name: ProductFeatureAppl
  relationType: many
  tags: [normal]
- bindFields: [productId]
  entityName: ProductKeyword
  name: ProductKeyword
  relationType: many
  tags: [normal]
- bindFields: [productId]
  entityName: ProductPrice
  name: ProductPrice
  relationType: many
  tags: [normal]
- bindFields: [productId]
  entityName: ProductPromoProduct
  name: ProductPromoProduct
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ProductReview
  name: ProductReview
  relationType: many
  tags: [normal]
- bindFields: [productId]
  entityName: ProductStoreSurveyAppl
  name: ProductStoreSurveyAppl
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ProductSubscriptionResource
  name: ProductSubscriptionResource
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: QuoteItem
  name: QuoteItem
  relationType: many
  tags: [skip]
- bindFields: [defaultShipmentBoxTypeId]
  entityName: ShipmentBoxType
  name: DefaultShipmentBoxType
  relationType: one
  tags: [skip]
- bindFields: [productId]
  entityName: ShipmentItem
  name: ShipmentItem
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ShipmentPackageContent
  name: SubShipmentPackageContent
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: ShipmentReceipt
  name: ShipmentReceipt
  relationType: many
  tags: [skip]
- bindFields: [productId]
  entityName: SupplierProduct
  name: SupplierProduct
  relationType: many
  tags: [skip]
- bindFields: [tenantId]
  entityName: Tenant
  name: Tenant
  relationType: one
  tags: [skip]
- bindFields: [createdByUserLogin]
  entityName: UserLogin
  name: CreatedByUserLogin
  relationType: one
  tags: [skip]
- bindFields: [lastModifiedByUserLogin]
  entityName: UserLogin
  name: LastModifiedByUserLogin
  relationType: one
  tags: [skip]
- bindFields: [productId]
  entityName: WorkEffortGoodStandard
  name: WorkEffortGoodStandard
  relationType: many
  tags: [skip]
