name: ProductStore
relationMarks:
- bindFields: [productStoreId]
  entityName: CustRequest
  name: CustRequest
  relationType: many
  tags: [skip]
- bindFields: [productStoreId]
  entityName: EbayConfig
  name: EbayConfig
  relationType: one-nofk
  tags: [skip]
- bindFields: [inventoryFacilityId]
  entityName: Facility
  name: Facility
  relationType: one
  tags: [skip]
- bindFields: [productStoreId]
  entityName: OrderHeader
  name: OrderHeader
  relationType: many
  tags: [skip]
- bindFields: [payToPartyId]
  entityName: Party
  name: Party
  relationType: one
  tags: [skip]
- bindFields: [productStoreId]
  entityName: ProductReview
  name: ProductReview
  relationType: many
  tags: [skip]
- bindFields: [productStoreId]
  entityName: ProductStoreCatalog
  name: ProductStoreCatalog
  relationType: many
  tags: [normal]
- bindFields: [productStoreId]
  entityName: ProductStoreEmailSetting
  name: ProductStoreEmailSetting
  relationType: many
  tags: [normal]
- bindFields: [productStoreId]
  entityName: ProductStoreFacility
  name: ProductStoreFacility
  relationType: many
  tags: [normal]
- bindFields: [productStoreId]
  entityName: ProductStoreFinActSetting
  name: ProductStoreFinActSetting
  relationType: many
  tags: [skip]
- bindFields: [productStoreId]
  entityName: ProductStoreKeywordOvrd
  name: ProductStoreKeywordOvrd
  relationType: many
  tags: [skip]
- bindFields: [productStoreId]
  entityName: ProductStorePaymentSetting
  name: ProductStorePaymentSetting
  relationType: many
  tags: [normal]
- bindFields: [productStoreId]
  entityName: ProductStorePromoAppl
  name: ProductStorePromoAppl
  relationType: many
  tags: [skip]
- bindFields: [productStoreId]
  entityName: ProductStoreRole
  name: ProductStoreRole
  relationType: many
  tags: [normal]
- bindFields: [productStoreId]
  entityName: ProductStoreSurveyAppl
  name: ProductStoreSurveyAppl
  relationType: many
  tags: [skip]
- bindFields: [productStoreId]
  entityName: Quote
  name: Quote
  relationType: many
  tags: [skip]
- bindFields: [vatTaxAuthGeoId, vatTaxAuthPartyId]
  entityName: TaxAuthority
  name: VatTaxAuthority
  relationType: one
  tags: [skip]
- bindFields: [productStoreId]
  entityName: TaxAuthorityRateProduct
  name: TaxAuthorityRateProduct
  relationType: many
  tags: [skip]
- bindFields: [tenantId]
  entityName: Tenant
  name: Tenant
  relationType: one
  tags: [skip]
- bindFields: [productStoreId]
  entityName: WebSite
  name: WebSite
  relationType: many
  tags: [normal]
