tenants:
  default:
    dataSource:
      url: jdbc:mysql://localhost:3306/hubs
      user: root
      password: root
    server:
      host: localhost
      port: 50056

  test:
    dataSource:
      url: jdbc:mysql://localhost:3306/testhubs
      user: root
      password: root
